<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>5 Regresión y correlación. | Estadística Empresarial</title>
<meta name="author" content="Miguel Ángel Tarancón Morán">
<meta name="description" content="Figura 5.1. Cuando la relación existe, toca ponerle números: intensidad y forma. En el capítulo anterior aprendimos a plantearnos una pregunta binaria —¿existe o no existe relación estadística...">
<meta name="generator" content="bookdown 0.46 with bs4_book()">
<meta property="og:title" content="5 Regresión y correlación. | Estadística Empresarial">
<meta property="og:type" content="book">
<meta property="og:url" content="https://teckel71.github.io/EstadisticaEmpresarial-book/regresion-correlacion.html">
<meta property="og:image" content="https://teckel71.github.io/EstadisticaEmpresarial-book/figuras/EE_portada.jpg">
<meta property="og:description" content="Figura 5.1. Cuando la relación existe, toca ponerle números: intensidad y forma. En el capítulo anterior aprendimos a plantearnos una pregunta binaria —¿existe o no existe relación estadística...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="5 Regresión y correlación. | Estadística Empresarial">
<meta name="twitter:description" content="Figura 5.1. Cuando la relación existe, toca ponerle números: intensidad y forma. En el capítulo anterior aprendimos a plantearnos una pregunta binaria —¿existe o no existe relación estadística...">
<meta name="twitter:image" content="https://teckel71.github.io/EstadisticaEmpresarial-book/figuras/EE_portada.jpg">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><link href="libs/Source_Serif_4-0.4.10/font.css" rel="stylesheet">
<link href="libs/JetBrains_Mono-0.4.10/font.css" rel="stylesheet">
<link href="libs/Source_Sans_3-0.4.10/font.css" rel="stylesheet">
<script src="libs/bs3compat-0.10.0/transition.js"></script><script src="libs/bs3compat-0.10.0/tabs.js"></script><script src="libs/bs3compat-0.10.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="assets/styles.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Estadística Empresarial</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"></a></li>
<li><a class="" href="prefacio.html">Prefacio</a></li>
<li><a class="" href="estadistica-economica-empresarial.html"><span class="header-section-number">1</span> Estadística Económica y Empresarial.</a></li>
<li><a class="" href="los-datos.html"><span class="header-section-number">2</span> Los datos.</a></li>
<li><a class="" href="variable-estadistica-unidimensional.html"><span class="header-section-number">3</span> Variable estadística unidimensional.</a></li>
<li><a class="" href="variable-estadistica-bidimensional.html"><span class="header-section-number">4</span> Variable estadística bidimensional y n-dimensional.</a></li>
<li><a class="active" href="regresion-correlacion.html"><span class="header-section-number">5</span> Regresión y correlación.</a></li>
<li><a class="" href="numeros-indice.html"><span class="header-section-number">6</span> Números índice.</a></li>
<li><a class="" href="introduccion-probabilidad.html"><span class="header-section-number">7</span> Introducción a la probabilidad.</a></li>
<li><a class="" href="variables-aleatorias.html"><span class="header-section-number">8</span> Variables aleatorias</a></li>
<li><a class="" href="modelos-discretos.html"><span class="header-section-number">9</span> Modelos de probabilidad discretos</a></li>
<li><a class="" href="modelos-continuos.html"><span class="header-section-number">10</span> Modelos de probabilidad continuos</a></li>
<li><a class="" href="tcl.html"><span class="header-section-number">11</span> Convergencia y teoremas centrales del límite</a></li>
<li><a class="" href="bibliograf%C3%ADa.html">Bibliografía</a></li>
<li><a class="" href="licencia.html">Licencia</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="regresion-correlacion" class="section level1" number="5">
<h1>
<span class="header-section-number">5</span> Regresión y correlación.<a class="anchor" aria-label="anchor" href="#regresion-correlacion"><i class="fas fa-link"></i></a>
</h1>
<div class="inline-figure"><img src="figuras/04_estelas.jpg" class="portada-img" style="width:100.0%"></div>
<div style="text-align: center;">
<p><strong>Figura 5.1.</strong> <span class="smallcaps">Cuando la relación existe, toca ponerle números: intensidad y forma.</span></p>
</div>
<p>En el capítulo anterior aprendimos a plantearnos una pregunta binaria —<em>¿existe o no existe relación estadística entre estas dos variables?</em>— y a contestarla con la ayuda de la tabla de correlación, las frecuencias condicionadas, el signo de la covarianza y, cuando ambas eran atributos, el estadístico ji-cuadrado. Terminamos la película con un puñado de casos en los que la respuesta era claramente afirmativa: en la plantilla de <em>Shuttlepod Movers</em> estudios y salario se movían juntos, en la flota de <span class="math inline">\(48\)</span> cargueros la antigüedad iba de la mano del tonelaje, en los tres astilleros galácticos la sede base dependía por completo del constructor.</p>
<p>Detectada la dependencia, entramos ahora en el terreno de las preguntas <strong>cuantitativas</strong>. Aceptemos que las dos variables se relacionan y planteemos, con toda la sangre fría:</p>
<ul>
<li>¿Con qué <strong>intensidad</strong> se relacionan? ¿Es una relación férrea, casi determinista, o apenas una tendencia con mucho ruido? Ese es el terreno del <strong>análisis de correlación</strong>.</li>
<li>¿Qué <strong>forma</strong> toma esa relación? ¿Podemos escribir una fórmula sencilla —una recta, una curva— que aproxime una variable a partir de la otra y permita <strong>prever</strong> valores? Ese es el terreno del <strong>análisis de regresión</strong>.</li>
</ul>
<p>Correlación y regresión son las dos caras de la misma moneda: la primera mide <em>cuánto</em> se parecen dos variables en su comportamiento; la segunda propone <em>cómo</em> se parecen. Ambas dan por sentado —y este es un requisito irrenunciable— que en la etapa anterior hemos comprobado que hay algo que medir. Ajustar una regresión a dos variables independientes es como calcular la media geométrica de un conjunto de temperaturas: técnicamente posible, epistemológicamente estéril.</p>
<p>Advertimos ya un punto que reaparecerá en varios sitios del capítulo. Como en el anterior, <strong>relación estadística no es relación causal</strong>. La regresión que ajustemos entre dos variables y el coeficiente de correlación que resumamos entre ellas son descripciones matemáticas de un patrón común de comportamiento; nada nos dice, por sí mismos, que una variable esté <em>causando</em> a la otra. La tentación de leer una regresión como una explicación causal es probablemente el error más frecuente entre quienes empiezan —y también, todo hay que decirlo, entre bastantes que ya deberían haber dejado de empezar.</p>
<div id="regresion-idea" class="section level2" number="5.1">
<h2>
<span class="header-section-number">5.1</span> Regresión: idea general.<a class="anchor" aria-label="anchor" href="#regresion-idea"><i class="fas fa-link"></i></a>
</h2>
<p>Supongamos que sobre cada individuo hemos medido dos variables cuantitativas <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> y que, tras la exploración del capítulo anterior, sabemos que existe alguna dependencia estadística entre ellas. Uno de los papeles puede desempeñarlo cualquiera, pero en la práctica solemos designar a una de ellas como <strong>variable explicada</strong> o <strong>dependiente</strong> (habitualmente <span class="math inline">\(Y\)</span>, la que queremos aproximar o predecir) y a la otra como <strong>variable explicativa</strong> o <strong>independiente</strong> (habitualmente <span class="math inline">\(X\)</span>, aquella que consideramos “informativa” sobre la primera).</p>
<p>El <strong>análisis de regresión</strong> consiste en encontrar una función matemática</p>
<p><span class="math display">\[
\hat{y}_i \;=\; f(x_i)
\]</span></p>
<p>que aproxime, lo mejor posible, los valores observados de <span class="math inline">\(Y\)</span> a partir de los de <span class="math inline">\(X\)</span>. El sombrero sobre la <span class="math inline">\(y\)</span> es una advertencia tipográfica útil: <span class="math inline">\(\hat{y}_i\)</span> no es un valor observado, sino un valor <em>propuesto</em> por el modelo; el valor observado —el que aparece en el fichero, el que registra la nave, el que cobra el empleado— seguirá siendo <span class="math inline">\(y_j\)</span>.</p>
<p>Como ninguna función <span class="math inline">\(f\)</span> podrá pasar por todos los puntos a la vez (el capítulo anterior nos advirtió que la vida no suele ser tan ordenada), la aproximación cometerá <strong>errores</strong>, uno por cada caso observado, que llamaremos <strong>residuos</strong>:</p>
<p><span class="math display">\[
e_{ij} \;=\; y_j - \hat{y}_i \;\;\Longleftrightarrow\;\; y_j \;=\; \hat{y}_i + e_{ij}.
\]</span></p>
<p>La descomposición anterior es la más importante del capítulo y conviene fijarla desde ya: <strong>valor observado = valor previsto por la regresión + residuo</strong>. La regresión será tanto más útil cuanto más pequeños sean, en promedio, esos residuos.</p>
<div id="regresion-simple-multiple" class="section level3" number="5.1.1">
<h3>
<span class="header-section-number">5.1.1</span> Regresión simple, regresión múltiple.<a class="anchor" aria-label="anchor" href="#regresion-simple-multiple"><i class="fas fa-link"></i></a>
</h3>
<p>Cuando la variable explicativa es una sola —el caso al que dedicaremos casi todo el capítulo— hablamos de <strong>regresión simple</strong>. Si hay varias, <span class="math inline">\(X_1, X_2, \ldots, X_p\)</span>, hablamos de <strong>regresión múltiple</strong>: la trataremos con brevedad al final, sin entrar en su maquinaria matricial.</p>
</div>
<div id="regresion-tipos" class="section level3" number="5.1.2">
<h3>
<span class="header-section-number">5.1.2</span> Dos caminos hacia la regresión: tipo I y tipo II.<a class="anchor" aria-label="anchor" href="#regresion-tipos"><i class="fas fa-link"></i></a>
</h3>
<p>Hay una distinción clásica en la tradición estadística española —Martín-Pliego, Ruiz-Maya, Martín-Guzmán— entre <strong>dos maneras distintas de construir la función de regresión</strong> a partir de la tabla de correlación. Ambas son descriptivas, ambas viven íntegramente en el marco de este capítulo y ambas hablan del mismo objeto, pero llegan a él por caminos muy distintos.</p>
<p><strong>Regresión de tipo I</strong> (también llamada <strong>intrínseca</strong>, o <strong>de la media</strong>, o <strong>en sentido estricto</strong>). Se apoya directamente en las <strong>distribuciones condicionadas</strong> que introdujimos en el capítulo anterior. Para cada valor <span class="math inline">\(x_i\)</span> de la variable explicativa, calculamos la <strong>media</strong> de la variable explicada condicionada a ese valor,</p>
<p><span class="math display">\[
\overline{y}_{\,\mid\, x_i} \;=\; \dfrac{1}{n_{i\bullet}} \sum_{j=1}^{k} y_j\, n_{ij},
\]</span></p>
<p>y unimos los puntos <span class="math inline">\((x_i,\ \overline{y}_{\,\mid\, x_i})\)</span>. Esa colección de puntos —o la curva que los une— <strong>es</strong> la regresión de tipo I. Su gran virtud es que no impone forma funcional alguna: la propia tabla de datos, a través de sus medias condicionadas, decide qué curva dibujar. Su gran limitación es que no entrega una expresión analítica manejable: no podemos escribir “<span class="math inline">\(\hat{y} = 628{,}21 + 11{,}61\,x\)</span>” ni hacer predicciones para valores de <span class="math inline">\(x\)</span> que no aparezcan en la tabla.</p>
<p><strong>Regresión de tipo II</strong> (también llamada <strong>funcional</strong>, o <strong>mínimo-cuadrática</strong>). Se elige a priori una <strong>forma funcional</strong> —una recta, una parábola, una potencial…— y se estiman sus parámetros por el criterio de mínimos cuadrados sobre toda la nube de puntos. El resultado es una función <span class="math inline">\(\hat{y}=f(x)\)</span> con parámetros numéricos concretos, que interpola y extrapola con la comodidad de un modelo cerrado.</p>
<p>La relación entre ambas es preciosa y se demuestra sin dificultad: <strong>ajustar por mínimos cuadrados la nube completa es equivalente a ajustar por mínimos cuadrados los puntos <span class="math inline">\((x_i,\ \overline{y}_{\,\mid\, x_i})\)</span> ponderados por las frecuencias marginales <span class="math inline">\(n_{i\bullet}\)</span></strong>. Dicho de otro modo, la regresión de tipo II es la <strong>traducción analítica operativa</strong> de la regresión de tipo I: la primera nos da la fotografía real del comportamiento condicionado; la segunda le pone forma matemática. Cuando elegimos bien la forma funcional del tipo II, ambas coinciden con exactitud sobre los puntos de las medias; cuando la elegimos mal, la del tipo II se aparta de la del tipo I y su <span class="math inline">\(R^2\)</span> paga el precio.</p>
<blockquote>
<p><strong>Aviso terminológico.</strong> Existe también un uso muy distinto del par “tipo I / tipo II” en la tradición biométrica anglosajona, donde se refiere a si solo la variable dependiente arrastra error de medida (tipo I, mínimos cuadrados ordinarios) o si ambas lo arrastran (tipo II, con métodos como el eje mayor tipificado o la regresión de Deming). No es la clasificación que empleamos aquí. Otra cosa distinta —también, a veces, fuente de confusión— es la diferencia entre la regresión <strong>descriptiva</strong> (sobre datos observados) y la regresión <strong>inferencial</strong> (sobre una población, con perturbación aleatoria <span class="math inline">\(\epsilon\)</span> del tipo <span class="math inline">\(Y = \beta_0 + \beta_1 X + \epsilon\)</span>). Esa distinción existe y es importante, pero <strong>no</strong> es la que la etiqueta “tipo I / tipo II” recoge en la tradición española; corresponde al paso de la estadística descriptiva a la inferencial y la trataremos en el bloque de Inferencia y Econometría.</p>
</blockquote>
<p>En este capítulo trabajaremos, salvo aviso, con <strong>regresión de tipo II</strong>: elegiremos formas funcionales (casi siempre la recta) y estimaremos sus parámetros por mínimos cuadrados. Pero en el ejemplo de la flota veremos también la lectura de tipo I sobre los mismos datos, para hacer visible la relación entre ambas.</p>
</div>
<div id="forma-funcional" class="section level3" number="5.1.3">
<h3>
<span class="header-section-number">5.1.3</span> Forma funcional y parámetros.<a class="anchor" aria-label="anchor" href="#forma-funcional"><i class="fas fa-link"></i></a>
</h3>
<p>Toda regresión consta de dos ingredientes que conviene distinguir con cuidado:</p>
<ul>
<li>La <strong>forma funcional</strong>, es decir, el tipo de función matemática que proponemos. Una recta, una parábola, una exponencial, una función logística… la elección es previa y refleja la hipótesis que hacemos sobre cómo se relacionan <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span>.</li>
<li>Los <strong>parámetros</strong>, esto es, las constantes que aparecen en la forma funcional (los coeficientes de la recta, los de la parábola, la base de la exponencial…), cuyos valores concretos hay que <strong>estimar</strong> a partir de los datos.</li>
</ul>
<p>Un puñado de ejemplos ilustra la variedad de formas funcionales que podemos plantear:</p>
<p><span class="math display">\[
\begin{array}{ll}
\hat{y}_i = a + b\, x_i                       &amp; \text{(lineal)},\\[4pt]
\hat{y}_i = a + b\, x_i + c\, x_i^{\,2}       &amp; \text{(parabólica)},\\[4pt]
\hat{y}_i = a\cdot x_i^{\,b}                  &amp; \text{(potencial)},\\[4pt]
\hat{y}_i = a\cdot b^{\,x_i}                  &amp; \text{(exponencial)},\\[4pt]
\hat{y}_i = \dfrac{1}{1 + e^{-(a + b\, x_i)}} &amp; \text{(logística)}.
\end{array}
\]</span></p>
<p>En cada forma, las letras <span class="math inline">\(a, b, c, \ldots\)</span> son los parámetros a estimar. En la lineal hay dos (<span class="math inline">\(a\)</span> y <span class="math inline">\(b\)</span>), en la parabólica tres, en la potencial y en la exponencial dos… La forma la propone el analista (a menudo mirando la nube de puntos); los parámetros los proponen los datos.</p>
<div class="callout-tip">
<p>La elección de la forma funcional es probablemente el momento más creativo —y más peligroso— del análisis. Una nube de puntos con forma de curva mansa se puede aproximar bien con una recta si uno cierra un ojo, o con un polinomio de grado siete si uno tiene menos escrúpulos que datos. La virtud del analista consiste en encontrar el equilibrio entre <strong>simplicidad</strong> (pocos parámetros, interpretación clara) y <strong>fidelidad</strong> (residuos pequeños). La regla del pulgar es preferir la forma más simple compatible con la estructura visible en la nube.</p>
</div>
</div>
<div id="minimos-cuadrados" class="section level3" number="5.1.4">
<h3>
<span class="header-section-number">5.1.4</span> El criterio de estimación: mínimos cuadrados.<a class="anchor" aria-label="anchor" href="#minimos-cuadrados"><i class="fas fa-link"></i></a>
</h3>
<p>Fijada la forma funcional, quedan por concretar los valores de los parámetros. ¿Qué criterio nos dice que unos valores son mejores que otros? La respuesta —clásica, sencilla, y con el sello de Gauss y Legendre desde principios del siglo XIX— es el <strong>criterio de mínimos cuadrados</strong>: elegir aquellos parámetros que hagan <strong>mínima la suma de los cuadrados de los residuos</strong>, ponderados por la frecuencia de cada caso:</p>
<p><span class="math display">\[
\min_{\text{parámetros}} \;\; \sum_{i=1}^{h}\sum_{j=1}^{k} e_{ij}^{\,2}\, n_{ij}
\;\;=\;\;
\min_{\text{parámetros}} \;\; \sum_{i=1}^{h}\sum_{j=1}^{k} \bigl(y_j - \hat{y}_i\bigr)^{2}\, n_{ij}.
\]</span></p>
<p>La elección del cuadrado no es caprichosa. Si sumásemos los residuos con su signo, los positivos y los negativos se cancelarían y el criterio sería trivialmente satisfecho por cualquier recta que pasara por el centro de la nube. Sumar los cuadrados evita esas cancelaciones, penaliza especialmente los residuos grandes (un residuo de <span class="math inline">\(10\)</span> pesa cuatro veces más que uno de <span class="math inline">\(5\)</span>) y —esto es lo que lo hace matemáticamente maravilloso— da lugar a un problema de minimización con solución cerrada, casi mágica, que se puede escribir con lápiz y papel. Otros criterios son concebibles (minimizar la suma de valores absolutos, minimizar el residuo máximo, etc.), pero el mínimo-cuadrático es el estándar universal y el que emplearemos.</p>
</div>
</div>
<div id="regresion-lineal-simple" class="section level2" number="5.2">
<h2>
<span class="header-section-number">5.2</span> Regresión lineal simple.<a class="anchor" aria-label="anchor" href="#regresion-lineal-simple"><i class="fas fa-link"></i></a>
</h2>
<p>De todas las formas funcionales posibles, la más simple —y la que utilizaremos de referencia durante todo el capítulo— es la <strong>recta</strong>:</p>
<p><span class="math display">\[
\hat{y}_i \;=\; a + b\, x_i.
\]</span></p>
<p>Los parámetros a estimar son el <strong>término independiente</strong> <span class="math inline">\(a\)</span> (el valor que la regresión asigna a <span class="math inline">\(\hat{y}\)</span> cuando <span class="math inline">\(x = 0\)</span>) y la <strong>pendiente</strong> <span class="math inline">\(b\)</span> (la variación de <span class="math inline">\(\hat{y}\)</span> ante un incremento unitario de <span class="math inline">\(x\)</span>). Aplicando el criterio de mínimos cuadrados,</p>
<p><span class="math display">\[
\min_{a, b} \;\; \sum_{i, j} \bigl(y_j - a - b\, x_i\bigr)^{2}\, n_{ij},
\]</span></p>
<p>y derivando respecto a <span class="math inline">\(a\)</span> y <span class="math inline">\(b\)</span> e igualando a cero, se obtiene el par de fórmulas que constituye la columna vertebral del capítulo:</p>
<p><span class="math display">\[
\boxed{\;\; \hat{b} \;=\; \dfrac{S_{xy}}{S_x^{\,2}}, \qquad
              \hat{a} \;=\; \overline{y} \;-\; \hat{b}\cdot \overline{x} \;\;}
\]</span></p>
<p>Merece la pena leerlas despacio.</p>
<p>La pendiente <span class="math inline">\(\hat{b}\)</span> es un cociente entre la <strong>covarianza</strong> <span class="math inline">\(S_{xy}\)</span> —esa medida bidimensional que introdujimos en el capítulo anterior— y la <strong>varianza de la variable explicativa</strong> <span class="math inline">\(S_x^{\,2}\)</span>. La covarianza aporta el signo y el “acoplamiento direccional” entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span>; la varianza de <span class="math inline">\(X\)</span> normaliza para que el resultado esté expresado en unidades correctas (unidades de <span class="math inline">\(Y\)</span> por cada unidad de <span class="math inline">\(X\)</span>). Por eso <span class="math inline">\(\hat{b}\)</span> hereda el signo de la covarianza: si <span class="math inline">\(S_{xy} &gt; 0\)</span>, la recta sube; si <span class="math inline">\(S_{xy} &lt; 0\)</span>, la recta baja.</p>
<p>El término independiente <span class="math inline">\(\hat{a}\)</span>, por su parte, se define de tal modo que la recta pase por el <strong>punto medio de la nube</strong>: el par <span class="math inline">\((\overline{x},\, \overline{y})\)</span>. Se comprueba en un segundo: si en <span class="math inline">\(\hat{y} = \hat{a} + \hat{b}\, x\)</span> sustituimos <span class="math inline">\(x = \overline{x}\)</span>, obtenemos</p>
<p><span class="math display">\[
\hat{a} + \hat{b}\, \overline{x} \;=\; \overline{y} - \hat{b}\, \overline{x} + \hat{b}\, \overline{x} \;=\; \overline{y}.
\]</span></p>
<p>Toda recta de regresión mínimo-cuadrática pasa por el centro de gravedad de la nube de puntos. Es una propiedad estética y práctica: la recta se ancla en el “punto promedio” y desde ahí gira para acomodarse lo mejor posible al resto.</p>
<div id="interpretacion-coeficientes" class="section level3" number="5.2.1">
<h3>
<span class="header-section-number">5.2.1</span> Interpretación de los coeficientes.<a class="anchor" aria-label="anchor" href="#interpretacion-coeficientes"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>
<span class="math inline">\(\hat{b}\)</span>: cuando <span class="math inline">\(x\)</span> aumenta en una unidad, <span class="math inline">\(\hat{y}\)</span> aumenta en <span class="math inline">\(\hat{b}\)</span> unidades. Es la <strong>variación media</strong> de la variable explicada asociada a un incremento unitario de la explicativa. Se lee en unidades de <span class="math inline">\(Y\)</span> por unidad de <span class="math inline">\(X\)</span>.</li>
<li>
<span class="math inline">\(\hat{a}\)</span>: valor que la regresión asigna a <span class="math inline">\(\hat{y}\)</span> cuando <span class="math inline">\(x = 0\)</span>. Su interpretación <em>literal</em> muchas veces no tiene sentido económico (¿qué es una empresa con “cero ingresos”?), y en la práctica se usa sobre todo como parámetro de ajuste que permite fijar la recta.</li>
</ul>
<p>Vale la pena insistir: el “<span class="math inline">\(+\)</span>” o el “<span class="math inline">\(-\)</span>” de <span class="math inline">\(\hat{b}\)</span> no habla de causalidad, sino de la dirección conjunta del movimiento. Y su magnitud depende de las unidades: si cambiamos <span class="math inline">\(X\)</span> de años a meses, <span class="math inline">\(\hat{b}\)</span> se dividirá por doce. Para leer intensidades sin la tiranía de las unidades tendremos que esperar al coeficiente de correlación.</p>
</div>
<div id="ejemplo-astilleros-reg" class="section level3" number="5.2.2">
<h3>
<span class="header-section-number">5.2.2</span> Un ejemplo completo: antigüedad y tonelaje en la flota de astilleros.<a class="anchor" aria-label="anchor" href="#ejemplo-astilleros-reg"><i class="fas fa-link"></i></a>
</h3>
<p>Volvamos a la muestra de <strong>48 cargueros</strong> del sector R-Stars construidos por <em>KORRIGAN</em>, <em>SELENE</em> y <em>ARCTURUS</em> que ya nos sirvió en el capítulo anterior para introducir la covarianza. Recordamos el escenario: para cada nave conocemos su <strong>antigüedad</strong> <span class="math inline">\(X\)</span> en años y su <strong>tonelaje</strong> máximo de carga útil <span class="math inline">\(Y\)</span> en miles de toneladas, y calculamos, sobre la tabla agrupada, una covarianza <span class="math inline">\(S_{xy}\)</span> claramente positiva. La pregunta que quedaba en el aire era: <em>¿podemos escribir una recta que resuma esa relación?</em></p>
<p>Aquí está la tabla de correlación (la misma con la que trabajamos en el capítulo anterior al introducir la covarianza), enriquecida ahora con las columnas y filas auxiliares que necesitamos para la regresión:</p>
<div class="inline-table"><table class="table table-hover table-condensed" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:center;">
<span class="math inline">\(x_i \setminus y_j\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(575\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(700\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(800\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(900\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(n_{i\bullet}\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(x_i n_{i\bullet}\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(x_i^{2} n_{i\bullet}\)</span>
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:center;">
2.5
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
14
</td>
<td style="text-align:center;">
35,00
</td>
<td style="text-align:center;">
87,50
</td>
</tr>
<tr>
<td style="text-align:center;">
7.5
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
120,00
</td>
<td style="text-align:center;">
900,00
</td>
</tr>
<tr>
<td style="text-align:center;">
12.5
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
112,50
</td>
<td style="text-align:center;">
1.406,25
</td>
</tr>
<tr>
<td style="text-align:center;">
17.5
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
140,00
</td>
<td style="text-align:center;">
2.450,00
</td>
</tr>
<tr>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
25,00
</td>
<td style="text-align:center;">
625,00
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math inline">\(n_{\bullet j}\)</span>
</td>
<td style="text-align:center;">
13
</td>
<td style="text-align:center;">
13
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
48
</td>
<td style="text-align:center;">
432,50
</td>
<td style="text-align:center;">
5.468,75
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math inline">\(y_j\, n_{\bullet j}\)</span>
</td>
<td style="text-align:center;">
7.475
</td>
<td style="text-align:center;">
9.100
</td>
<td style="text-align:center;">
9.600
</td>
<td style="text-align:center;">
9.000
</td>
<td style="text-align:center;">
35.175
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math inline">\(y_j^{2}\, n_{\bullet j}\)</span>
</td>
<td style="text-align:center;">
4.298.125
</td>
<td style="text-align:center;">
6.370.000
</td>
<td style="text-align:center;">
7.680.000
</td>
<td style="text-align:center;">
8.100.000
</td>
<td style="text-align:center;">
26.448.125
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
</tbody>
</table></div>
<p>Con las marcas de clase <span class="math inline">\(x_i \in \{2{,}5;\ 7{,}5;\ 12{,}5;\ 17{,}5;\ 25\}\)</span> e <span class="math inline">\(y_j \in \{575;\ 700;\ 800;\ 900\}\)</span>, los momentos respecto al origen son los que ya calculamos en el capítulo 3, cuando obtuvimos la covarianza:</p>
<p><span class="math display">\[
a_{10} \;=\; 9,0104, \qquad
a_{01} \;=\; 732,8125, \qquad
a_{20} \;=\; 113,9323,
\]</span> <span class="math display">\[
a_{02} \;=\; 551.002,6042, \qquad
a_{11} \;=\; 6.983,0729.
\]</span></p>
<p>Los momentos centrales que nos interesan son la varianza de <span class="math inline">\(X\)</span>, la varianza de <span class="math inline">\(Y\)</span> y la covarianza:</p>
<p><span class="math display">\[
S_x^{\,2} \;=\; a_{20} - a_{10}^{\,2} \;=\; 32,7447,\qquad
S_y^{\,2} \;=\; a_{02} - a_{01}^{\,2} \;=\; 13.988,44,
\]</span> <span class="math display">\[
S_{xy}   \;=\; a_{11} - a_{10}\cdot a_{01} \;=\; 380,1270.
\]</span></p>
<p>Aplicando ahora las fórmulas de la recta mínimo-cuadrática,</p>
<p><span class="math display">\[
\hat{b} \;=\; \dfrac{S_{xy}}{S_x^{\,2}} \;=\; \dfrac{380,1270}{32,7447} \;=\; 11,6088,
\]</span></p>
<p><span class="math display">\[
\hat{a} \;=\; \overline{y} - \hat{b}\cdot \overline{x} \;=\; 732,8125 \;-\; 11,6088\cdot 9,0104 \;=\; 628,2122.
\]</span></p>
<p>La recta de regresión de tonelaje sobre antigüedad es, por tanto,</p>
<p><span class="math display">\[
\boxed{\;\; \hat{y}_i \;=\; 628,21 \;+\; 11,61\cdot x_i \;\;}
\]</span></p>
<p>y su lectura práctica es transparente: cada año adicional de antigüedad se asocia, en promedio, con unos <strong>11,61 miles de toneladas más de capacidad de carga</strong>. Un carguero recién estrenado (<span class="math inline">\(x=0\)</span>) tendría, según la recta, unas <span class="math inline">\(628\)</span> mil toneladas de tonelaje típico; un carguero de <span class="math inline">\(10\)</span> años se acerca a las <span class="math inline">\(744\)</span> mil; uno de <span class="math inline">\(20\)</span>, a las <span class="math inline">\(860\)</span>. La flota galáctica se ha ido —dicho llanamente— <em>aligerando</em>.</p>
<p>Podemos comprobar visualmente el ajuste sobre la nube de puntos original (los <span class="math inline">\(48\)</span> cargueros sin agrupar):</p>
<div class="inline-figure"><img src="EstadisticaEmpresarial_files/figure-html/astilleros-scatter-reg-1.png" alt="" width="100%" style="display: block; margin: auto;"></div>
<div style="text-align: center;">
<p><strong>Figura 5.2.</strong> Diagrama de dispersión de la flota y recta ajustada por mínimos cuadrados.</p>
</div>
<p>La recta atraviesa la nube con obediencia razonable, pero es evidente que la dispersión alrededor de ella no es despreciable: hay cargueros viejos y ligeros, cargueros nuevos y pesados. La nube tiene una tendencia clara, sí; pero también un ruido considerable. Cuantificar cuán bien —o cuán mal— la recta representa a la nube es la tarea de la sección siguiente.</p>
<p>Antes de eso, un pequeño paréntesis muy útil en la práctica moderna: todo lo que hemos calculado a mano cabe en dos líneas de <code>R</code>. La función <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> (por <em>linear model</em>) ajusta la recta y guarda todos los resultados en un objeto que después puede consultarse con <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code>, <code><a href="https://rdrr.io/r/stats/coef.html">coef()</a></code>, <code><a href="https://rdrr.io/r/stats/residuals.html">residuals()</a></code> y compañía:</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">modelo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">TONELAJE</span> <span class="op">~</span> <span class="va">ANTIG</span>, data <span class="op">=</span> <span class="va">astilleros</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">modelo</span><span class="op">)</span></span></code></pre></div>
<pre><code>## (Intercept)       ANTIG 
##   615.01272    12.64932</code></pre>
<p>Los dos números que devuelve —<code>(Intercept)</code> y <code>ANTIG</code>— son exactamente <span class="math inline">\(\hat{a}\)</span> y <span class="math inline">\(\hat{b}\)</span> que hemos obtenido a pulso, salvo diferencias de redondeo por trabajar sobre los datos individuales en lugar de la tabla agrupada. La mecánica manual del capítulo tiene una función pedagógica; en la vida real, todo el mundo hace <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>. Ver que ambos caminos llevan al mismo sitio es parte del aprendizaje.</p>
</div>
<div id="tipo1-astilleros" class="section level3" number="5.2.3">
<h3>
<span class="header-section-number">5.2.3</span> Regresión de tipo I sobre la flota.<a class="anchor" aria-label="anchor" href="#tipo1-astilleros"><i class="fas fa-link"></i></a>
</h3>
<p>Un buen momento para asomarnos a la regresión de tipo I que anunciábamos en la sección anterior. Con la misma tabla agrupada de la flota, calculamos, para cada intervalo de antigüedad, la <strong>media condicionada</strong> del tonelaje:</p>
<div class="inline-table"><table class="table table-hover table-condensed" style="font-size: 13px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:center;">
<span class="math inline">\(x_i\)</span> (años)
</th>
<th style="text-align:center;">
<span class="math inline">\(n_{i\bullet}\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(\overline{y}_{\,\mid\, x_i}\)</span> (miles de t)
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:center;">
2.5
</td>
<td style="text-align:center;">
14
</td>
<td style="text-align:center;">
626.79
</td>
</tr>
<tr>
<td style="text-align:center;">
7.5
</td>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
743.75
</td>
</tr>
<tr>
<td style="text-align:center;">
12.5
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
811.11
</td>
</tr>
<tr>
<td style="text-align:center;">
17.5
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
787.50
</td>
</tr>
<tr>
<td style="text-align:center;">
25.0
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
900.00
</td>
</tr>
</tbody>
</table></div>
<p>Los cinco puntos <span class="math inline">\((2{,}5;\ 626{,}79)\)</span>, <span class="math inline">\((7{,}5;\ 743{,}75)\)</span>, <span class="math inline">\((12{,}5;\ 811{,}11)\)</span>, <span class="math inline">\((17{,}5;\ 787{,}50)\)</span>, <span class="math inline">\((25;\ 900)\)</span> <strong>son</strong> la regresión de tipo I: no imponemos ninguna forma funcional, las medias condicionadas hablan por sí solas. Se lee que el tonelaje típico crece con la antigüedad, pero no de forma perfectamente monótona (el cuarto intervalo se aparta ligeramente hacia abajo) y con un último punto —la solitaria nave de <span class="math inline">\(25\)</span> años— que arrastra la tendencia al alza. Es lo que la nube de puntos condicionada nos dice de verdad, sin la simplificación de una recta.</p>
<p>Comparemos gráficamente ambas regresiones sobre los mismos datos:</p>
<div class="inline-figure"><img src="EstadisticaEmpresarial_files/figure-html/astilleros-tipo1-tipo2-1.png" alt="" width="100%" style="display: block; margin: auto;"></div>
<div style="text-align: center;">
<p><strong>Figura 5.3.</strong> Regresión de tipo I (puntos oscuros: medias condicionadas del tonelaje por intervalo de antigüedad, con tamaño proporcional a la frecuencia) frente a regresión de tipo II (recta mínimo-cuadrática) sobre la flota.</p>
</div>
<p>Y aquí una comprobación numérica que ilustra la propiedad de equivalencia: si ajustamos por mínimos cuadrados una recta a los <strong>cinco puntos de las medias condicionadas</strong> ponderándolos por sus frecuencias <span class="math inline">\(n_{i\bullet}\)</span>, obtenemos exactamente los mismos coeficientes que ajustar la recta a los <span class="math inline">\(48\)</span> cargueros originales. La regresión de tipo II es —literalmente— la traducción analítica lineal de la regresión de tipo I.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># MCO sobre los 5 puntos (xi, medias_cond) ponderados por n_i</span></span>
<span><span class="va">xbar_c</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">xi</span> <span class="op">*</span> <span class="va">ni_ast</span><span class="op">)</span> <span class="op">/</span> <span class="va">N_ast</span></span>
<span><span class="va">ybar_c</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">medias_cond</span> <span class="op">*</span> <span class="va">ni_ast</span><span class="op">)</span> <span class="op">/</span> <span class="va">N_ast</span></span>
<span><span class="va">Sxy_c</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">xi</span> <span class="op">-</span> <span class="va">xbar_c</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="va">medias_cond</span> <span class="op">-</span> <span class="va">ybar_c</span><span class="op">)</span> <span class="op">*</span> <span class="va">ni_ast</span><span class="op">)</span> <span class="op">/</span> <span class="va">N_ast</span></span>
<span><span class="va">Sx2_c</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">xi</span> <span class="op">-</span> <span class="va">xbar_c</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">ni_ast</span><span class="op">)</span> <span class="op">/</span> <span class="va">N_ast</span></span>
<span><span class="va">b_tipo1</span> <span class="op">&lt;-</span> <span class="va">Sxy_c</span> <span class="op">/</span> <span class="va">Sx2_c</span></span>
<span><span class="va">a_tipo1</span> <span class="op">&lt;-</span> <span class="va">ybar_c</span> <span class="op">-</span> <span class="va">b_tipo1</span> <span class="op">*</span> <span class="va">xbar_c</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>a_tipo1 <span class="op">=</span> <span class="va">a_tipo1</span>, b_tipo1 <span class="op">=</span> <span class="va">b_tipo1</span><span class="op">)</span>   <span class="co"># coinciden con a_hat y b_hat</span></span></code></pre></div>
<pre><code>##   a_tipo1   b_tipo1 
## 628.21224  11.60881</code></pre>
</div>
<div id="prediccion-extrapolacion" class="section level3" number="5.2.4">
<h3>
<span class="header-section-number">5.2.4</span> Predicción y una advertencia importante.<a class="anchor" aria-label="anchor" href="#prediccion-extrapolacion"><i class="fas fa-link"></i></a>
</h3>
<p>Una vez estimada la recta, uno de sus usos naturales es <strong>prever</strong> el valor de <span class="math inline">\(Y\)</span> para valores de <span class="math inline">\(X\)</span> no observados directamente. Si un potencial cliente pregunta cuál sería el tonelaje típico de un carguero con <span class="math inline">\(22\)</span> años de servicio, la recta responde sin dudar:</p>
<p><span class="math display">\[
\hat{y}(22) \;=\; 628,21 + 11,61\cdot 22 \;=\; 883,61 \ \text{miles de toneladas}.
\]</span></p>
<p>Predicción y previsión son la aplicación más popular de la regresión: no en vano media econometría del mundo se dedica a estimar rectas para preguntarles cosas después. Ahora bien, un aviso que las guías galácticas de buenas prácticas repiten cada mes en su portada:</p>
<blockquote>
<p><strong>Advertencia sobre la extrapolación.</strong> La recta se ha ajustado sobre un rango de valores concreto de la variable explicativa. En nuestro caso, la antigüedad de los cargueros observados va aproximadamente de <span class="math inline">\(2\)</span> a <span class="math inline">\(22\)</span> años. <strong>Fuera de ese rango, la regresión pierde toda garantía.</strong> Preguntar por el tonelaje de un carguero de <span class="math inline">\(80\)</span> años no es hacer una previsión; es hacer un acto de fe. La estructura que hemos observado puede quebrarse en los extremos, aparecer cambios de régimen, o senc­illamente entrar en zonas donde no hay datos que respalden la extrapolación.</p>
</blockquote>
<p>Por otro lado, la recta <em>no es</em> una promesa sobre casos individuales: para un carguero concreto de <span class="math inline">\(22\)</span> años, el tonelaje real puede desviarse notablemente del pronóstico. La regresión predice <strong>promedios</strong>, no individuos. Si el residuo típico es de <span class="math inline">\(70\)</span> mil toneladas, el pronóstico “<span class="math inline">\(893\)</span>” hay que leerlo como “en torno a <span class="math inline">\(893\)</span>, con un margen de error del orden de decenas de miles de toneladas”.</p>
</div>
<div id="outliers" class="section level3" number="5.2.5">
<h3>
<span class="header-section-number">5.2.5</span> La sensibilidad a valores atípicos.<a class="anchor" aria-label="anchor" href="#outliers"><i class="fas fa-link"></i></a>
</h3>
<p>Un aspecto que la fórmula <span class="math inline">\(\hat{b} = S_{xy}/S_x^{\,2}\)</span> oculta pero que aparece con toda su virulencia en cuanto uno tiene datos reales entre las manos: la regresión mínimo-cuadrática <strong>es muy sensible a los valores atípicos</strong>. Basta con un solo punto lo bastante alejado del patrón general para que la recta gire de forma llamativa y el <span class="math inline">\(R^{2}\)</span> se venga abajo.</p>
<p>Ilustrémoslo con un experimento controlado. Simulamos una nube “limpia” de <span class="math inline">\(30\)</span> observaciones que siguen una relación aproximadamente lineal —piénsese en una flota nueva, bien gestionada— y añadimos después un solo carguero anómalo: uno de los prototipos de emergencia de <em>Wraith Industries</em>, extremadamente ligero pese a llevar años en servicio, que quedaría fuera del comportamiento habitual del sector:</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:outlier-demo"></span>
<img src="EstadisticaEmpresarial_files/figure-html/outlier-demo-1.png" alt="Efecto de un único valor atípico sobre la recta de regresión. Comparen la línea negra continua (con el atípico) con la discontinua ámbar (sin él): el ajuste cambia sustancialmente y el $R^{2}$ se hunde." width="100%"><p class="caption">
Figure 5.1: Efecto de un único valor atípico sobre la recta de regresión. Comparen la línea negra continua (con el atípico) con la discontinua ámbar (sin él): el ajuste cambia sustancialmente y el <span class="math inline">\(R^{2}\)</span> se hunde.
</p>
</div>
<p>La caída del <span class="math inline">\(R^{2}\)</span> es brutal —del <span class="math inline">\(83\,\%\)</span> al <span class="math inline">\(26\,\%\)</span>— y la pendiente y la ordenada se distorsionan aunque solo hayamos añadido <strong>una</strong> observación al conjunto original de treinta. Ese es el precio de haber elegido el criterio de mínimos cuadrados: penalizar el residuo al cuadrado hace que un solo caso muy alejado tenga una fuerza desproporcionada. Alternativas más robustas —regresión mediana, regresión con función de pérdida de Huber, mínimos absolutos— existen y forman parte del arsenal de la estadística moderna; en un curso introductorio nos basta con haber visto el peligro y saber <strong>mirar la nube de puntos</strong> antes de dejarnos guiar por los coeficientes.</p>
</div>
</div>
<div id="bondad-ajuste" class="section level2" number="5.3">
<h2>
<span class="header-section-number">5.3</span> Bondad del ajuste: el coeficiente de determinación.<a class="anchor" aria-label="anchor" href="#bondad-ajuste"><i class="fas fa-link"></i></a>
</h2>
<p>Ya sabemos ajustar una recta a una nube de puntos. La pregunta pendiente es: <strong>¿lo hace bien?</strong> Dicho de otro modo: ¿en qué medida los valores previstos <span class="math inline">\(\hat{y}_i\)</span> reproducen los valores realmente observados <span class="math inline">\(y_j\)</span>? Necesitamos una medida numérica de la <strong>calidad del ajuste</strong> que sea comparable entre distintas regresiones y no dependa de las unidades de las variables.</p>
<p>La idea que hay debajo es tan intuitiva que casi resulta demasiado simple. Descompongamos el desvío de cada observación respecto a la media de <span class="math inline">\(Y\)</span>:</p>
<p><span class="math display">\[
y_j - \overline{y} \;=\; \underbrace{\hat{y}_i - \overline{y}}_{\text{parte explicada}} \;+\; \underbrace{e_{ij}}_{\text{parte no explicada}}.
\]</span></p>
<p>La lectura es la que sugiere el diagrama: parte de lo que un valor observado se aparta de la media global la “explica” la regresión (la recta lo lleva desde el nivel <span class="math inline">\(\overline{y}\)</span> hasta <span class="math inline">\(\hat{y}_i\)</span>), y otra parte queda sin explicar (el residuo <span class="math inline">\(e_{ij}\)</span>, el trecho que queda entre el pronóstico y el valor real). Elevando al cuadrado, sumando sobre todos los casos con sus frecuencias, dividiendo por <span class="math inline">\(N\)</span> y aprovechando una propiedad que la regresión mínimo-cuadrática garantiza —el término cruzado se anula— se llega a la <strong>descomposición de la varianza</strong>:</p>
<p><span class="math display">\[
\underbrace{\dfrac{\sum_j (y_j - \overline{y})^{2}\, n_{\bullet j}}{N}}_{S_y^{\,2}\ \text{(varianza total)}}
\;\;=\;\;
\underbrace{\dfrac{\sum_i (\hat{y}_i - \overline{y})^{2}\, n_{i\bullet}}{N}}_{S_{\hat{y}}^{\,2}\ \text{(varianza explicada)}}
\;\;+\;\;
\underbrace{\dfrac{\sum_{i,j} e_{ij}^{\,2}\, n_{ij}}{N}}_{S_e^{\,2}\ \text{(varianza residual)}}.
\]</span></p>
<p>En palabras: la varianza total de <span class="math inline">\(Y\)</span> se descompone en la parte que la regresión es capaz de reproducir (la varianza de los pronósticos <span class="math inline">\(\hat{y}_i\)</span>) más la parte que queda como ruido (la varianza de los residuos). Como los tres términos son cantidades positivas y la primera es fija —depende solo de los datos— el problema de ajustar la regresión se puede releer así: cuanto <strong>mayor</strong> sea <span class="math inline">\(S_{\hat{y}}^{\,2}\)</span>, <strong>mejor</strong> el ajuste; cuanto <strong>menor</strong> sea <span class="math inline">\(S_e^{\,2}\)</span>, mejor también. Y estas dos cantidades varían al unísono.</p>
<p>De ahí la definición canónica del <strong>coeficiente de determinación</strong>:</p>
<p><span class="math display">\[
\boxed{\;\; R^{2} \;=\; \dfrac{S_{\hat{y}}^{\,2}}{S_y^{\,2}} \;=\; 1 - \dfrac{S_e^{\,2}}{S_y^{\,2}} \;\;}
\]</span></p>
<p><span class="math inline">\(R^2\)</span> es, sin más, la <strong>proporción de la varianza de</strong> <span class="math inline">\(Y\)</span> que la regresión es capaz de reproducir. Como cociente de dos varianzas positivas —una menor o igual que la otra— cumple <span class="math inline">\(0 \le R^2 \le 1\)</span>. Y su lectura no puede ser más agradecida:</p>
<ul>
<li>
<span class="math inline">\(R^{2}\)</span> próximo a <span class="math inline">\(1\)</span>: la regresión captura casi toda la variabilidad de <span class="math inline">\(Y\)</span>. El ajuste es excelente.</li>
<li>
<span class="math inline">\(R^{2}\)</span> próximo a <span class="math inline">\(0\)</span>: la regresión no captura nada. La recta es prácticamente horizontal y pasa por <span class="math inline">\(\overline{y}\)</span>; conocer <span class="math inline">\(X\)</span> no ayuda a predecir <span class="math inline">\(Y\)</span>.</li>
<li>Valores intermedios se interpretan como porcentajes: un <span class="math inline">\(R^{2}\)</span> de <span class="math inline">\(0{,}70\)</span> significa que el modelo reproduce el <span class="math inline">\(70\,\%\)</span> de la variabilidad observada.</li>
</ul>
<p>En el caso lineal, un pequeño desarrollo algebraico entrega una fórmula compacta muy útil para calcular <span class="math inline">\(R^{2}\)</span> directamente a partir de los momentos:</p>
<p><span class="math display">\[
R^{2} \;=\; \dfrac{S_{xy}^{\,2}}{S_x^{\,2}\cdot S_y^{\,2}}.
\]</span></p>
<div id="R2-astilleros" class="section level3" number="5.3.1">
<h3>
<span class="header-section-number">5.3.1</span> Vuelta a la flota.<a class="anchor" aria-label="anchor" href="#R2-astilleros"><i class="fas fa-link"></i></a>
</h3>
<p>Con los momentos que ya tenemos calculados para el ejemplo de los astilleros:</p>
<p><span class="math display">\[
R^{2} \;=\; \dfrac{S_{xy}^{\,2}}{S_x^{\,2}\cdot S_y^{\,2}} \;=\;
\dfrac{380,1270^{2}}{32,7447\cdot 13.988,44} \;=\; 0,3155.
\]</span></p>
<p>Interpretación: la recta que hemos estimado reproduce, aproximadamente, el <strong>31,5,%</strong> de la variabilidad del tonelaje de la flota. No es un mal resultado —hay un patrón claro, y una recta lo captura razonablemente— pero tampoco es un ajuste espectacular: casi <strong>dos tercios</strong> de la variabilidad observada del tonelaje son atribuibles a factores distintos de la antigüedad. Basta con mirar el gráfico anterior para comprender por qué: cargueros del mismo astillero y de antigüedades similares tienen tonelajes muy distintos, y hay una segmentación evidente por astillero (KORRIGAN construye típicamente más pesado que ARCTURUS). Una regresión de tonelaje sobre astillero, o una regresión múltiple que incluya ambos factores, mejoraría muy probablemente el ajuste.</p>
<div class="callout-tip">
<p>Un <span class="math inline">\(R^{2}\)</span> moderado no es sinónimo de “regresión mala”: es sinónimo de “conocer <span class="math inline">\(X\)</span> no basta para saberlo todo sobre <span class="math inline">\(Y\)</span>”. En Ciencias Sociales, un <span class="math inline">\(R^{2}\)</span> de <span class="math inline">\(0{,}3\)</span> suele ser un logro respetable —los seres humanos son notoriamente ruidosos— mientras que en Física un <span class="math inline">\(R^{2}\)</span> de <span class="math inline">\(0{,}9\)</span> puede indicar un error de calibración. Todo depende del terreno de juego.</p>
</div>
</div>
<div id="residuos-diagnostico" class="section level3" number="5.3.2">
<h3>
<span class="header-section-number">5.3.2</span> Los residuos como diagnóstico.<a class="anchor" aria-label="anchor" href="#residuos-diagnostico"><i class="fas fa-link"></i></a>
</h3>
<p>El <span class="math inline">\(R^{2}\)</span> resume la calidad del ajuste en un único número, pero los <strong>residuos</strong> son los que dicen <em>dónde</em> falla el modelo. Si están repartidos al azar alrededor del cero, sin patrón visible, la regresión ha hecho su trabajo. Si en cambio se agrupan sistemáticamente por encima o por debajo de la línea del cero para ciertos valores de <span class="math inline">\(X\)</span> o para ciertos subgrupos de la muestra, la nube está pidiendo un modelo mejor.</p>
<p>En el caso de la flota, un gráfico de <strong>residuos frente a valores ajustados</strong>, coloreado por astillero, revela con toda claridad la fuente del <span class="math inline">\(R^{2}\)</span> modesto:</p>
<div class="inline-figure"><img src="EstadisticaEmpresarial_files/figure-html/astilleros-residuos-1.png" alt="" width="100%" style="display: block; margin: auto;"></div>
<div style="text-align: center;">
<p><strong>Figura 5.4.</strong> Residuos frente a valores ajustados en la flota, por astillero. La estructura del color muestra que la antigüedad, por sí sola, no capta la segmentación por constructor.</p>
</div>
<p>La lectura es inequívoca. Los residuos <strong>no</strong> están mezclados al azar: KORRIGAN aparece sistemáticamente por encima del cero (sus cargueros son consistentemente más pesados de lo que la antigüedad sola predice), ARCTURUS ocupa la banda inferior (más ligeros de lo esperado) y SELENE se sitúa en la zona intermedia. La antigüedad, tomada aislada, mezcla tres poblaciones que se comportan diferente. <strong>El diagnóstico de residuos ha detectado con precisión qué le falta al modelo</strong>, y sugiere la corrección natural: incluir la identidad del astillero como segunda variable explicativa. Volveremos a esta idea al final del capítulo, en la sección de regresión múltiple.</p>
</div>
</div>
<div id="correlacion" class="section level2" number="5.4">
<h2>
<span class="header-section-number">5.4</span> Correlación.<a class="anchor" aria-label="anchor" href="#correlacion"><i class="fas fa-link"></i></a>
</h2>
<p>El coeficiente de determinación <span class="math inline">\(R^{2}\)</span> nos dice, en un solo número entre <span class="math inline">\(0\)</span> y <span class="math inline">\(1\)</span>, con qué calidad la regresión reproduce los datos. Ahora bien, esa calidad depende de dos cosas distintas que conviene no confundir:</p>
<ol style="list-style-type: decimal">
<li>Si la <strong>forma funcional</strong> propuesta es adecuada. Con datos que se distribuyen en forma de <span class="math inline">\(U\)</span>, una recta obtendrá un <span class="math inline">\(R^{2}\)</span> paupérrimo aunque la relación estadística sea muy intensa: el problema está en la elección de la forma, no en la relación.</li>
<li>Si la <strong>relación estadística real</strong> entre las dos variables es intensa o débil. Con datos que se dispersan mucho alrededor de la mejor recta posible, el <span class="math inline">\(R^{2}\)</span> será bajo aunque la forma funcional sea la correcta.</li>
</ol>
<p>En el análisis de <strong>correlación</strong> damos por supuesto lo primero —hemos elegido bien la forma funcional, típicamente la lineal— y usamos el ajuste para medir lo segundo: cuán intensa es la relación. La medida canónica es el <strong>coeficiente de correlación lineal</strong>, que definimos como</p>
<p><span class="math display">\[
R \;=\; \pm\sqrt{R^{2}} \;=\; \pm\sqrt{\,1 - \dfrac{S_e^{\,2}}{S_y^{\,2}}\,},
\]</span></p>
<p>con el signo de la covarianza (positivo si <span class="math inline">\(S_{xy} &gt; 0\)</span>, negativo si <span class="math inline">\(S_{xy} &lt; 0\)</span>). En el caso lineal, la expresión se compacta hasta la elegantísima forma cerrada</p>
<p><span class="math display">\[
\boxed{\;\; R \;=\; \dfrac{S_{xy}}{S_x \cdot S_y} \;\;}
\]</span></p>
<p>donde <span class="math inline">\(S_x\)</span> y <span class="math inline">\(S_y\)</span> son las desviaciones típicas marginales. La lectura es doble:</p>
<ul>
<li>
<strong>Signo:</strong> heredado de la covarianza. Positivo cuando las dos variables tienden a moverse en el mismo sentido; negativo cuando lo hacen en sentidos opuestos.</li>
<li>
<strong>Magnitud:</strong> el valor absoluto de <span class="math inline">\(R\)</span> mide la intensidad de la relación lineal. Por construcción, <span class="math inline">\(-1 \le R \le +1\)</span>. Los extremos representan situaciones ideales:
<ul>
<li>
<span class="math inline">\(R = +1\)</span>: todos los puntos caen exactamente sobre una recta de pendiente positiva. Dependencia lineal perfecta y directa.</li>
<li>
<span class="math inline">\(R = -1\)</span>: todos los puntos caen exactamente sobre una recta de pendiente negativa. Dependencia lineal perfecta e inversa.</li>
<li>
<span class="math inline">\(R = 0\)</span>: no hay relación lineal (aunque, cuidado, sí puede haber relaciones no lineales que <span class="math inline">\(R\)</span> no ve).</li>
</ul>
</li>
</ul>
<p>Una escala orientativa —no un tribunal universal— que suele emplearse para calificar la intensidad de <span class="math inline">\(R\)</span>:</p>
<div class="inline-table"><table class="table table-sm">
<caption>Escala orientativa para <span class="math inline">\(|R|\)</span> en el análisis descriptivo.</caption>
<thead><tr class="header">
<th align="center"><span class="math inline">\(|R|\)</span></th>
<th align="left">Lectura habitual</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center">
<span class="math inline">\(0{,}0\)</span>–<span class="math inline">\(0{,}2\)</span>
</td>
<td align="left">Relación lineal muy débil o inexistente.</td>
</tr>
<tr class="even">
<td align="center">
<span class="math inline">\(0{,}2\)</span>–<span class="math inline">\(0{,}5\)</span>
</td>
<td align="left">Relación lineal débil.</td>
</tr>
<tr class="odd">
<td align="center">
<span class="math inline">\(0{,}5\)</span>–<span class="math inline">\(0{,}7\)</span>
</td>
<td align="left">Relación lineal moderada.</td>
</tr>
<tr class="even">
<td align="center">
<span class="math inline">\(0{,}7\)</span>–<span class="math inline">\(0{,}9\)</span>
</td>
<td align="left">Relación lineal fuerte.</td>
</tr>
<tr class="odd">
<td align="center">
<span class="math inline">\(0{,}9\)</span>–<span class="math inline">\(1{,}0\)</span>
</td>
<td align="left">Relación lineal muy fuerte, casi determinista.</td>
</tr>
</tbody>
</table></div>
<div style="text-align: center;">
<p><strong>Tabla 5.1.</strong> Escala orientativa para <span class="math inline">\(|R|\)</span> en el análisis descriptivo.</p>
</div>
<div id="R-astilleros" class="section level3" number="5.4.1">
<h3>
<span class="header-section-number">5.4.1</span> El coeficiente de correlación en la flota.<a class="anchor" aria-label="anchor" href="#R-astilleros"><i class="fas fa-link"></i></a>
</h3>
<p>Retomamos, por última vez en esta sección, la flota de astilleros. Como <span class="math inline">\(S_{xy} &gt; 0\)</span>, el signo de <span class="math inline">\(R\)</span> es positivo, y</p>
<p><span class="math display">\[
R \;=\; \dfrac{S_{xy}}{S_x \cdot S_y} \;=\;
\dfrac{380,1270}{\sqrt{32,7447}\cdot \sqrt{13.988,44}} \;=\; 0,5617.
\]</span></p>
<p>Un <span class="math inline">\(R = 0,56\)</span> cae en el terreno de las relaciones <strong>moderadas</strong>: coherente con lo que ya sabíamos —la nube de puntos tenía tendencia clara pero considerable dispersión— y con el <span class="math inline">\(R^{2}\)</span> que habíamos calculado, del que este <span class="math inline">\(R\)</span> es literalmente la raíz cuadrada con el signo de la covarianza.</p>
<p>Un detalle numérico digno de mención: si comparamos el <span class="math inline">\(R^{2}\)</span> que hemos obtenido sobre la tabla <strong>agrupada</strong> (<span class="math inline">\(R^{2} = 0,315\)</span>) con el que se obtendría sobre los <strong>datos individuales</strong> de los <span class="math inline">\(48\)</span> cargueros sin agrupar (aproximadamente <span class="math inline">\(0{,}39\)</span>), veremos que el segundo es ligeramente mayor. La razón es sencilla: al agrupar en intervalos, sustituimos cada valor por la marca de clase de su intervalo y con ello perdemos algo de información sobre la variabilidad. En estadística descriptiva es un compromiso habitual —ganamos en manejabilidad, perdemos algo en precisión— y forma parte de la mecánica de trabajar con tablas.</p>
</div>
<div id="dos-rectas" class="section level3" number="5.4.2">
<h3>
<span class="header-section-number">5.4.2</span> Las dos rectas de regresión.<a class="anchor" aria-label="anchor" href="#dos-rectas"><i class="fas fa-link"></i></a>
</h3>
<p>En el capítulo anterior, al presentar las frecuencias condicionadas, insistimos en que un mismo cruce admite dos lecturas simétricas —<span class="math inline">\(X\)</span> dada <span class="math inline">\(Y\)</span> y <span class="math inline">\(Y\)</span> dada <span class="math inline">\(X\)</span>— que responden a preguntas distintas. Esa dualidad reaparece con toda su fuerza en el análisis de regresión: sobre una misma nube de puntos podemos ajustar <strong>dos rectas</strong>, no solo una.</p>
<p>Hasta ahora hemos trabajado con la <strong>recta de <span class="math inline">\(Y\)</span> sobre <span class="math inline">\(X\)</span></strong>, la que responde a “<em>conocida la antigüedad, ¿cuánto tonelaje cabe esperar?</em>” y minimiza los residuos verticales <span class="math inline">\(y_j - \hat{y}_i\)</span>. Pero podríamos plantear igualmente la pregunta inversa: “<em>conocido el tonelaje, ¿qué antigüedad cabría esperar en un carguero así?</em>”. La respuesta es la <strong>recta de <span class="math inline">\(X\)</span> sobre <span class="math inline">\(Y\)</span></strong>, que minimiza los residuos horizontales <span class="math inline">\(x_i - \hat{x}_j\)</span> y tiene por fórmula</p>
<p><span class="math display">\[
\hat{x}_j \;=\; \hat{a}' + \hat{b}'\, y_j, \qquad
\hat{b}' \;=\; \dfrac{S_{xy}}{S_y^{\,2}}, \qquad
\hat{a}' \;=\; \overline{x} - \hat{b}'\, \overline{y}.
\]</span></p>
<p>Nótese la asimetría: la pendiente de la recta de <span class="math inline">\(Y\)</span> sobre <span class="math inline">\(X\)</span> divide por <span class="math inline">\(S_x^{\,2}\)</span>; la de la recta de <span class="math inline">\(X\)</span> sobre <span class="math inline">\(Y\)</span> divide por <span class="math inline">\(S_y^{\,2}\)</span>. Son distintas y <strong>no</strong> son la misma recta despejada al revés (salvo en un caso trivial que veremos enseguida).</p>
<p>En la flota:</p>
<p><span class="math display">\[
\hat{b}' \;=\; \dfrac{S_{xy}}{S_y^{\,2}} \;=\; \dfrac{380,13}{13.988,44} \;=\; 0,02717, \qquad
\hat{a}' \;=\; 9,01 \;-\; 0,02717\cdot 732,81 \;=\; -10,90.
\]</span></p>
<p>Sus lecturas son diferentes pero complementarias. La primera recta dice “por cada año más de antigüedad, esperemos <span class="math inline">\(11{,}61\)</span> mil toneladas más de tonelaje”; la segunda dice “por cada mil toneladas más de tonelaje, esperemos <span class="math inline">\(0{,}027\)</span> años más de antigüedad”. Preguntas distintas, respuestas distintas.</p>
<p><strong>Y ahora la propiedad que da la conexión con la correlación.</strong> Multiplicando las dos pendientes,</p>
<p><span class="math display">\[
\hat{b}\cdot \hat{b}' \;=\; \dfrac{S_{xy}}{S_x^{\,2}}\cdot \dfrac{S_{xy}}{S_y^{\,2}} \;=\; \dfrac{S_{xy}^{\,2}}{S_x^{\,2}\cdot S_y^{\,2}} \;=\; R^{2}.
\]</span></p>
<p>Es decir: <strong>el producto de las pendientes de las dos rectas de regresión es exactamente el coeficiente de determinación</strong>. En nuestro caso, <span class="math inline">\(11,6088\cdot 0,02717 = 0,3155\)</span>, que coincide (salvo redondeo) con el <span class="math inline">\(R^{2} = 0,3155\)</span> que calculamos antes. Es una elegantísima identidad que suele memorizarse por su forma compacta:</p>
<p><span class="math display">\[
\boxed{\;\; \hat{b}\cdot \hat{b}' \;=\; R^{2} \;\;}
\]</span></p>
<p>Y esa fórmula nos dice también qué relación geométrica hay entre las dos rectas:</p>
<ul>
<li>Cuando <span class="math inline">\(R^{2} = 1\)</span>, el producto <span class="math inline">\(\hat{b}\cdot \hat{b}'\)</span> vale <span class="math inline">\(1\)</span>; las dos pendientes son inversas y las dos rectas <strong>coinciden</strong>. Es la dependencia lineal perfecta: conocer una variable determina exactamente la otra, en ambas direcciones.</li>
<li>Cuando <span class="math inline">\(R^{2} = 0\)</span>, el producto es <span class="math inline">\(0\)</span>; una de las pendientes es cero, la recta correspondiente es horizontal y la otra es vertical. Las dos rectas se cruzan <strong>perpendicularmente</strong>, y coincide con el hecho de que no hay relación lineal alguna.</li>
<li>Cuando <span class="math inline">\(R^{2}\)</span> es intermedio, las dos rectas forman una “tijera” alrededor del centro de gravedad de la nube, cuya apertura se estrecha a medida que <span class="math inline">\(R^{2}\)</span> crece hacia <span class="math inline">\(1\)</span>.</li>
</ul>
<p>Un gráfico lo hace evidente:</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:dos-rectas-plot"></span>
<img src="EstadisticaEmpresarial_files/figure-html/dos-rectas-plot-1.png" alt="Las dos rectas de regresión sobre la flota. Se cruzan en el centro de gravedad $(\overline{x},\ \overline{y})$ y su apertura mide indirectamente la dispersión de la nube." width="100%"><p class="caption">
Figure 5.2: Las dos rectas de regresión sobre la flota. Se cruzan en el centro de gravedad <span class="math inline">\((\overline{x},\ \overline{y})\)</span> y su apertura mide indirectamente la dispersión de la nube.
</p>
</div>
<p>Las dos rectas se abren en abanico desde el punto <span class="math inline">\((\overline{x},\ \overline{y})\)</span> señalado con la cruz ámbar. Si el <span class="math inline">\(R^{2}\)</span> hubiese sido más alto, las dos rectas estarían más cerca la una de la otra; si hubiese sido más bajo, se abrirían aún más hasta acercarse a la perpendicularidad. <strong>La apertura del abanico es, literalmente, una lectura visual de <span class="math inline">\(R^{2}\)</span></strong>.</p>
</div>
<div id="R-rstars-ing-costop" class="section level3" number="5.4.3">
<h3>
<span class="header-section-number">5.4.3</span> Un ejemplo con ajuste excelente: ingresos y costos operativos en R-Stars.<a class="anchor" aria-label="anchor" href="#R-rstars-ing-costop"><i class="fas fa-link"></i></a>
</h3>
<p>Un <span class="math inline">\(R^{2}\)</span> moderado como el de la flota puede dejarnos con dudas legítimas sobre si la regresión “vale la pena”. Para calibrar, echemos un vistazo a un cruce en el que la relación lineal es contundente. Sobre las <span class="math inline">\(N = 300\)</span> compañías del sector R-Stars, dispongamos en un lado los <strong>ingresos</strong> de cada compañía (<code>ING</code>, en miles de PAVOs) y en el otro sus <strong>costos operativos</strong> (<code>COSTOP</code>, también en miles de PAVOs). La intuición económica es clara —a mayor volumen de actividad, mayores costes de operación— y los datos, esta vez, no van a discutirle nada al intuición.</p>
<div class="inline-figure"><img src="EstadisticaEmpresarial_files/figure-html/rstars-ing-costop-scatter-1.png" alt="" width="100%" style="display: block; margin: auto;"></div>
<div style="text-align: center;">
<p><strong>Figura 5.5.</strong> Nube de puntos y recta de regresión sobre las 300 compañías de la muestra R-Stars.</p>
</div>
<p>Los coeficientes de la recta ajustada son</p>
<p><span class="math display">\[
\hat{a} \;=\; -9,41, \qquad
\hat{b} \;=\; 0,4909,
\]</span></p>
<p>es decir,</p>
<p><span class="math display">\[
\hat{y}_i \;=\; -9,41 \;+\; 0,4909\cdot x_i,
\]</span></p>
<p>y por cada mil PAVOs adicionales de ingresos, los costos operativos se elevan, en promedio, unos <span class="math inline">\(491\)</span> PAVOs (dicho en corto: cerca de la mitad de cada PAVO facturado acaba absorbido por el coste operativo, un margen bruto que en el sector interestelar no sorprende a nadie). El coeficiente de correlación y el de determinación,</p>
<p><span class="math display">\[
R^{2} \;=\; 0,8968, \qquad
R \;=\; 0,9470,
\]</span></p>
<p>reflejan una relación lineal <strong>muy fuerte, casi determinista</strong>: la recta reproduce el <span class="math inline">\(89,7\,\%\)</span> de la variabilidad de los costes. Es lo que en la práctica se llama, con toda propiedad, una relación <em>bien portada</em>.</p>
</div>
<div id="anscombe" class="section level3" number="5.4.4">
<h3>
<span class="header-section-number">5.4.4</span> Un aviso importante: el cuarteto de Anscombe.<a class="anchor" aria-label="anchor" href="#anscombe"><i class="fas fa-link"></i></a>
</h3>
<p>Antes de dar por buena la lectura del <span class="math inline">\(R\)</span> y del <span class="math inline">\(R^{2}\)</span> como resumen de una relación, conviene detenerse en uno de los ejemplos más citados —y más aleccionadores— de la historia de la estadística. En <span class="math inline">\(1973\)</span>, el estadístico británico Francis Anscombe publicó un pequeño artículo con cuatro conjuntos de datos que compartían <strong>exactamente</strong> las mismas medias, las mismas varianzas, la misma covarianza, la misma recta ajustada y <strong>el mismo <span class="math inline">\(R^{2}\)</span></strong> (con cuatro decimales de precisión), y que sin embargo, al dibujar la nube, se comportaban de formas radicalmente distintas.</p>
<p>Es el llamado <strong>cuarteto de Anscombe</strong>, que forma parte del propio <code>R</code> como <code><a href="https://rdrr.io/r/datasets/anscombe.html">datasets::anscombe</a></code>. Reproducirlo lleva quince líneas:</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:anscombe"></span>
<img src="EstadisticaEmpresarial_files/figure-html/anscombe-1.png" alt="El cuarteto de Anscombe. Los cuatro conjuntos comparten media, varianza, covarianza, coeficientes de la recta ajustada y $R^{2}$ hasta la segunda cifra decimal. Solo el conjunto (I) responde a un ajuste lineal genuino." width="100%"><p class="caption">
Figure 5.3: El cuarteto de Anscombe. Los cuatro conjuntos comparten media, varianza, covarianza, coeficientes de la recta ajustada y <span class="math inline">\(R^{2}\)</span> hasta la segunda cifra decimal. Solo el conjunto (I) responde a un ajuste lineal genuino.
</p>
</div>
<p>Las cuatro fotografías son un manifiesto pedagógico. En el panel (I), la recta ajusta un patrón lineal auténtico, y el <span class="math inline">\(R^{2} \approx 0{,}67\)</span> tiene el sentido natural que le asignamos. En (II), la relación es claramente <strong>cuadrática</strong>: la recta lineal es una respuesta equivocada a la pregunta correcta, y el <span class="math inline">\(R^{2}\)</span> solo la refleja porque la parábola es aproximadamente lineal en un rango. En (III), hay una relación lineal <strong>perfecta</strong> en todos los puntos menos uno; ese único <strong>outlier</strong> tira de la recta hacia sí y contamina el resumen. En (IV), el <span class="math inline">\(R^{2}\)</span> y la recta están <strong>dictados por un solo punto</strong> situado muy lejos de los demás: retirarlo dejaría al modelo sin nada que decir, porque los diez restantes tienen todos <span class="math inline">\(x=8\)</span> y no informan sobre la pendiente. Es lo que en la jerga se llama un <strong>punto de alta palanca</strong> (o <em>leverage</em>).</p>
<p>La moraleja se enuncia con toda sencillez: <strong>el <span class="math inline">\(R^{2}\)</span> y los coeficientes de la recta son resúmenes, no diagnósticos</strong>. Nunca deberían leerse sin dibujar la nube. En 2013, los estadísticos Justin Matejka y George Fitzmaurice llevaron la idea al extremo con el <strong>Datasaurus Dozen</strong>, doce conjuntos de puntos con los mismos estadísticos hasta la segunda cifra decimal que dibujan, según el caso, un dinosaurio, una estrella o dos círculos concéntricos. Si Anscombe fue un aviso, el Datasaurus es una carcajada; ambos apuntan al mismo consejo profesional: <strong>mira la nube antes de creerte el número</strong>.</p>
</div>
<div id="correlacion-no-causal" class="section level3" number="5.4.5">
<h3>
<span class="header-section-number">5.4.5</span> Correlación no implica causalidad (bis).<a class="anchor" aria-label="anchor" href="#correlacion-no-causal"><i class="fas fa-link"></i></a>
</h3>
<p>El aviso ya lo dimos en el capítulo anterior, pero conviene actualizarlo con la munición del presente. Un coeficiente de correlación alto entre dos variables no permite —por sí mismo— extraer ninguna conclusión sobre relaciones de causa a efecto. Es fácil imaginarse el desastre argumental que se puede montar con un <span class="math inline">\(R\)</span> elevado y un poco de mala fe:</p>
<ul>
<li>Ingresos y costos operativos de las compañías R-Stars tienen <span class="math inline">\(R = 0,95\)</span>. ¿Los ingresos “causan” los costos? Uno podría defenderlo. ¿Los costos “causan” los ingresos? Otro podría defender lo contrario con la misma insolencia. La verdad prosaica es que ambos crecen porque las compañías crecen: los dos son manifestaciones de una tercera variable —el <strong>tamaño</strong> de la actividad— que actúa como causa común.</li>
<li>La antigüedad y el tonelaje de los cargueros correlacionan positivamente. Pero la antigüedad no <em>causa</em> el tonelaje (los cargueros no engordan con los años); lo que ocurre es que los astilleros galácticos han cambiado su cartera de productos con el tiempo, y hoy fabrican más ligero que hace dos décadas. La causa vuelve a estar en una variable externa, la política comercial del sector.</li>
</ul>
<p>En la literatura anglosajona se ha popularizado la expresión <em>“correlation is not causation”</em> hasta convertirla casi en un cliché de sobremesa; el cliché, sin embargo, protege de errores muy caros. La regla operativa que interesa recordar es que la correlación —y la regresión que la acompaña— <strong>describen</strong> un patrón de comportamiento común entre dos variables. Interpretarlo causalmente exige, además, un modelo teórico y un diseño de investigación que permitan descartar otras explicaciones. La estadística descriptiva es un observador imparcial: no señala culpables.</p>
</div>
</div>
<div id="generalizacion" class="section level2" number="5.5">
<h2>
<span class="header-section-number">5.5</span> Generalización de la regresión.<a class="anchor" aria-label="anchor" href="#generalizacion"><i class="fas fa-link"></i></a>
</h2>
<p>Hasta aquí hemos jugado en un tablero cómodo: una única variable explicativa y una recta como forma funcional. Los dos supuestos se pueden —y se deben— relajar en muchas situaciones reales. Cerramos el capítulo con dos vías de generalización.</p>
<div id="no-lineales" class="section level3" number="5.5.1">
<h3>
<span class="header-section-number">5.5.1</span> Casos no lineales: linealización.<a class="anchor" aria-label="anchor" href="#no-lineales"><i class="fas fa-link"></i></a>
</h3>
<p>Cuando la nube de puntos no dibuja una tendencia rectilínea sino claramente curvada, ajustar una recta puede ser un ejercicio de estoicismo estadístico: el <span class="math inline">\(R^{2}\)</span> se resiente, los residuos muestran un patrón sistemático (por ejemplo, primero positivos, luego negativos, luego positivos otra vez) y la interpretación pierde solidez. En muchas ocasiones, sin embargo, la relación no lineal se puede <strong>linealizar</strong> —transformar los valores de una o de ambas variables— de modo que sobre las nuevas variables sí quepa una recta.</p>
<p>Los dos casos clásicos son:</p>
<ul>
<li>
<strong>Potencial:</strong> <span class="math inline">\(\hat{y}_i = a\cdot x_i^{\,b}\)</span>. Tomando logaritmos, <span class="math inline">\(\log \hat{y}_i = \log a + b\cdot \log x_i\)</span>: si sustituimos <span class="math inline">\(x_i^{*} = \log x_i\)</span> e <span class="math inline">\(y_j^{*} = \log y_j\)</span>, obtenemos una recta con pendiente <span class="math inline">\(b\)</span> y ordenada <span class="math inline">\(\log a\)</span>. Los parámetros <span class="math inline">\(a\)</span> y <span class="math inline">\(b\)</span> se recuperan al final (<span class="math inline">\(a = e^{\log a}\)</span>, <span class="math inline">\(b\)</span> tal cual).</li>
<li>
<strong>Exponencial:</strong> <span class="math inline">\(\hat{y}_i = a\cdot b^{\,x_i}\)</span>. Tomando logaritmos, <span class="math inline">\(\log \hat{y}_i = \log a + x_i\cdot \log b\)</span>: una recta sobre <span class="math inline">\(x\)</span> y <span class="math inline">\(\log y\)</span>.</li>
</ul>
<p>La estrategia es siempre la misma: se transforman los datos, se ajusta una regresión lineal mínimo-cuadrática sobre las variables transformadas, y se <strong>deshace</strong> la transformación para leer los parámetros originales. El <span class="math inline">\(R^{2}\)</span> del ajuste linealizado suele ser mucho más alto que el del ajuste directo, y refleja la calidad real de la aproximación.</p>
</div>
<div id="curva-aprendizaje" class="section level3" number="5.5.2">
<h3>
<span class="header-section-number">5.5.2</span> Un caso ilustrativo: la curva de aprendizaje en <em>Hyperdrive Express</em>.<a class="anchor" aria-label="anchor" href="#curva-aprendizaje"><i class="fas fa-link"></i></a>
</h3>
<p>La compañía <strong>Hyperdrive Express</strong> —que ya nos ha acompañado en varios capítulos como paradigma de gran operador galáctico— acaba de incorporar a su hangar central un módulo experimental de revisión de motores de curvatura. Sus ingenieros han cronometrado el <strong>tiempo</strong> (en minutos) que un tripulante recién incorporado tarda en completar una revisión completa a medida que <strong>acumula operaciones</strong>. Los datos, sobre diez fases de la formación de un tripulante representativo, son:</p>
<div class="inline-table"><table class="table table-hover table-condensed" style="font-size: 13px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:center;">
Operaciones acumuladas (<span class="math inline">\(x_i\)</span>)
</th>
<th style="text-align:center;">
Tiempo por revisión (<span class="math inline">\(y_j\)</span>, min)
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
61.5
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
46.8
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
42.2
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
36.9
</td>
</tr>
<tr>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
30.0
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
26.5
</td>
</tr>
<tr>
<td style="text-align:center;">
15
</td>
<td style="text-align:center;">
25.2
</td>
</tr>
<tr>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
21.9
</td>
</tr>
<tr>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
17.8
</td>
</tr>
<tr>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
15.7
</td>
</tr>
</tbody>
</table></div>
<div style="text-align: center;">
<p><strong>Tabla 5.2.</strong> Curva de aprendizaje de un tripulante en el módulo de revisión de motores de Hyperdrive Express.</p>
</div>
<p>La lectura intuitiva es la de siempre en estos casos: al principio se aprende mucho por cada operación (la caída inicial es abrupta) y, con el tiempo, la mejora se vuelve marginal. La nube de puntos, en efecto, dibuja una curva de descenso rápido que luego se aplana. Ajustar una recta directamente da un <span class="math inline">\(R^{2}\)</span> modesto y unos residuos con patrón sistemático:</p>
<p><span class="math display">\[
\hat{y}_i \;=\; 42,77 \;+\; (-0,721)\cdot x_i, \qquad R^{2} \;=\; 0,605.
\]</span></p>
<p>Un <span class="math inline">\(R^{2}\)</span> del <span class="math inline">\(61\,\%\)</span> es razonable, pero si observamos la nube y la recta se aprecia el problema: la recta sobreestima al principio, subestima en la parte media y vuelve a fallar en la cola. La curvatura de los datos pide, sencillamente, otra forma funcional.</p>
<p>Proponemos entonces una <strong>regresión potencial</strong>: <span class="math inline">\(\hat{y}_i = a\cdot x_i^{\,b}\)</span>. Tomando logaritmos y ajustando por mínimos cuadrados sobre las variables transformadas, obtenemos</p>
<p><span class="math display">\[
\log \hat{y}_i \;=\; 4,118 \;+\; (-0,350)\cdot \log x_i, \qquad R^{2}_{\log} \;=\; 0,9929,
\]</span></p>
<p>que deshaciendo la transformación se lee como</p>
<p><span class="math display">\[
\boxed{\;\; \hat{y}_i \;=\; 61,42\cdot x_i^{\,-0,350} \;\;}
\]</span></p>
<p>Un <span class="math inline">\(R^{2}\)</span> del <span class="math inline">\(99,3\,\%\)</span>: es la relación <strong>casi determinista</strong> que el fenómeno pedía. La exponente <span class="math inline">\(b = -0,350\)</span> (negativa, en el rango típico de las curvas de aprendizaje industriales) nos dice que cada vez que las operaciones acumuladas se duplican, el tiempo por revisión se reduce en un factor <span class="math inline">\(2^{-0,350} \approx 0,785\)</span>, esto es, aproximadamente un <span class="math inline">\(22\,\%\)</span>. Es la clásica “tasa de aprendizaje” que los responsables de operaciones citan en sus informes anuales, y que ahora podemos leer directamente en la pendiente linealizada.</p>
<p>Comparemos gráficamente ambos ajustes:</p>
<div class="inline-figure"><img src="EstadisticaEmpresarial_files/figure-html/curva-scatter-1.png" alt="" width="100%" style="display: block; margin: auto;"></div>
<div style="text-align: center;">
<p><strong>Figura 5.6.</strong> Datos de la tabla anterior con dos ajustes: lineal (gris, discontinuo) y potencial (negro, continuo).</p>
</div>
<p>La lección que sacamos es doble. Primera: <strong>no toda relación estadística es lineal</strong>, y forzar una recta cuando la nube pide una curva penaliza el ajuste. Segunda: <strong>muchas relaciones no lineales son linealizables</strong>, y basta con transformar las variables (típicamente con logaritmos) para volver al terreno confortable de la regresión lineal. La forma final del modelo es no lineal —<span class="math inline">\(\hat{y} = a\cdot x^{b}\)</span>— pero la estimación se ha hecho con la misma maquinaria mínimo-cuadrática que veníamos utilizando.</p>
</div>
<div id="regresion-multiple" class="section level3" number="5.5.3">
<h3>
<span class="header-section-number">5.5.3</span> Regresión múltiple.<a class="anchor" aria-label="anchor" href="#regresion-multiple"><i class="fas fa-link"></i></a>
</h3>
<p>La segunda vía de generalización es admitir <strong>varias variables explicativas</strong> simultáneamente. Cuando la variable explicada <span class="math inline">\(Y\)</span> depende de <span class="math inline">\(p\)</span> variables <span class="math inline">\(X_1, X_2, \ldots, X_p\)</span>, el modelo lineal más natural es</p>
<p><span class="math display">\[
\hat{y}_i \;=\; b_0 + b_1\cdot x_{1i} + b_2\cdot x_{2i} + \cdots + b_p\cdot x_{pi},
\]</span></p>
<p>con <span class="math inline">\(p+1\)</span> parámetros a estimar. El criterio de mínimos cuadrados sigue siendo el mismo —minimizar la suma de los cuadrados de los residuos—, pero su resolución requiere ya álgebra lineal (matrices de datos, sistemas de ecuaciones normales…) y se aborda con propiedad en un curso posterior de Econometría.</p>
<p>La motivación práctica, en cambio, se comprende de inmediato retomando el hilo que dejamos abierto en la sección de los residuos. Habíamos visto que <strong>la antigüedad, por sí sola</strong>, explica cerca del <span class="math inline">\(39\,\%\)</span> de la variabilidad del tonelaje sobre los datos individuales de la flota. El gráfico de residuos nos había avisado con luces de neón que los tres astilleros ocupan bandas distintas: quedaba estructura sin capturar. La regresión múltiple es exactamente la herramienta para meterla dentro del modelo.</p>
<p>Añadimos como segunda variable explicativa la <strong>identidad del astillero</strong>. Al ser categórica, se codifica con <strong>variables</strong> <strong><em>dummy</em></strong> (indicadoras): tomando <code>ARCTURUS</code> como categoría de referencia, definimos <span class="math inline">\(D_K = 1\)</span> si el carguero es de <code>KORRIGAN</code> y <span class="math inline">\(0\)</span> en otro caso, y análogamente <span class="math inline">\(D_S\)</span> para <code>SELENE</code>. El modelo pasa a ser</p>
<p><span class="math display">\[
\widehat{\text{TONELAJE}}_i \;=\; b_0 \;+\; b_1\cdot \text{ANTIG}_i \;+\; b_2\cdot D_{K,i} \;+\; b_3\cdot D_{S,i},
\]</span></p>
<p>y su estimación —esta vez sí, la delegamos con toda tranquilidad en <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>— entrega:</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">modelo_simple</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">TONELAJE</span> <span class="op">~</span> <span class="va">ANTIG</span>, data <span class="op">=</span> <span class="va">astilleros</span><span class="op">)</span></span>
<span><span class="va">modelo_mult</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">TONELAJE</span> <span class="op">~</span> <span class="va">ANTIG</span> <span class="op">+</span> <span class="va">ASTILLERO</span>, data <span class="op">=</span> <span class="va">astilleros</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Resumen de ambos ajustes</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  Modelo   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Simple: TONELAJE ~ ANTIG"</span>,</span>
<span>               <span class="st">"Múltiple: TONELAJE ~ ANTIG + ASTILLERO"</span><span class="op">)</span>,</span>
<span>  R2       <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">modelo_simple</span><span class="op">)</span><span class="op">$</span><span class="va">r.squared</span>,</span>
<span>               <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">modelo_mult</span><span class="op">)</span><span class="op">$</span><span class="va">r.squared</span><span class="op">)</span>,</span>
<span>  R2_ajust <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">modelo_simple</span><span class="op">)</span><span class="op">$</span><span class="va">adj.r.squared</span>,</span>
<span>               <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">modelo_mult</span><span class="op">)</span><span class="op">$</span><span class="va">adj.r.squared</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div>
<pre><code>##                                   Modelo        R2  R2_ajust
## 1               Simple: TONELAJE ~ ANTIG 0.3939398 0.3807646
## 2 Múltiple: TONELAJE ~ ANTIG + ASTILLERO 0.7055211 0.6854430</code></pre>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">modelo_mult</span><span class="op">)</span></span></code></pre></div>
<pre><code>##       (Intercept)             ANTIG ASTILLEROKORRIGAN   ASTILLEROSELENE 
##         722.46076           1.44467         107.06812        -111.48040</code></pre>
<p>El salto es sustancial. El <span class="math inline">\(R^{2}\)</span> pasa del <span class="math inline">\(39\,\%\)</span> al <strong><span class="math inline">\(71\,\%\)</span></strong>: incluir el astillero como segunda variable <strong>duplica</strong> casi la varianza explicada. Y los coeficientes tienen ahora una lectura estupenda. La ordenada <span class="math inline">\(b_0 \approx 722\)</span> es el tonelaje típico de un carguero recién estrenado del astillero de referencia (<code>ARCTURUS</code>); la pendiente de antigüedad, <span class="math inline">\(b_1 \approx 1{,}44\)</span>, es mucho más pequeña que la del modelo simple (<span class="math inline">\(12{,}65\)</span>), y no por casualidad: buena parte del “efecto antigüedad” que veíamos antes era en realidad <strong>el efecto astillero disfrazado</strong> —los astilleros más productivos y con carteras más pesadas tienden a tener flotas más antiguas—. Los coeficientes de las <em>dummies</em> dicen que un carguero de <code>KORRIGAN</code> pesa, en promedio, unos <span class="math inline">\(107\)</span> mil toneladas más que uno equivalente de <code>ARCTURUS</code>, y uno de <code>SELENE</code>, unos <span class="math inline">\(111\)</span> mil menos.</p>
<p>Este es el mismo fenómeno de las <strong>variables acechantes</strong> —variables ocultas que explican parte de lo que un modelo simple atribuía a otra— que la paradoja de Simpson mostraba en el capítulo anterior sobre las tablas de contingencia. La regresión múltiple es su antídoto cuantitativo: al incluir la variable acechante como explicativa, la pendiente de la variable original recupera su interpretación limpia.</p>
</div>
<div id="r2-ajustado" class="section level3" number="5.5.4">
<h3>
<span class="header-section-number">5.5.4</span> Un aviso conceptual sobre el R² ajustado.<a class="anchor" aria-label="anchor" href="#r2-ajustado"><i class="fas fa-link"></i></a>
</h3>
<p>En el resultado anterior hemos comparado también un <strong><span class="math inline">\(R^{2}\)</span> ajustado</strong>, novedad que conviene explicar brevemente. El <span class="math inline">\(R^{2}\)</span> ordinario tiene una limitación estructural: <strong>siempre crece —o al menos no baja— al añadir cualquier variable al modelo, aunque esa variable sea puro ruido</strong>. Es una propiedad matemática de la descomposición de la varianza. Si comparamos dos modelos anidados por su <span class="math inline">\(R^{2}\)</span> ordinario, el modelo con más variables gana automáticamente, lo cual no es un criterio útil.</p>
<p>El <span class="math inline">\(R^{2}\)</span> ajustado corrige esa asimetría penalizando la introducción de variables:</p>
<p><span class="math display">\[
R^{2}_{\text{aj}} \;=\; 1 \;-\; (1 - R^{2})\cdot \dfrac{N-1}{N-p-1},
\]</span></p>
<p>donde <span class="math inline">\(N\)</span> es el número de observaciones y <span class="math inline">\(p\)</span> el número de variables explicativas. Su lectura es paralela a la del <span class="math inline">\(R^{2}\)</span> (cuanto mayor, mejor), pero solo crece cuando la nueva variable <strong>aporta más de lo que cuesta</strong>. En el ejemplo de la flota, ambos suben: incluir el astillero es una ganancia real, no un adorno.</p>
<p>Un aviso final: pasar de una a varias variables explicativas no es solo una cuestión técnica. Aparecen problemas nuevos —correlaciones altas entre las propias explicativas (la temida <strong>multicolinealidad</strong>), interpretaciones parciales que exigen fijar mentalmente el resto de variables, riesgo de <strong>sobreajuste</strong> cuando <span class="math inline">\(p\)</span> crece— que la regresión simple no plantea. La regresión múltiple, y toda la familia moderna de modelos que descienden de ella (regularización, regresión logística, modelos lineales generalizados, y en último término gran parte del <em>machine learning</em> supervisado), merecerán, en su momento, cursos propios. Pero el ADN sigue siendo el que hemos visto en este capítulo: encontrar los parámetros que hacen mínimos, en promedio, los residuos al cuadrado.</p>
</div>
</div>
<div id="recapitulacion-cap05" class="section level2" number="5.6">
<h2>
<span class="header-section-number">5.6</span> Recapitulación.<a class="anchor" aria-label="anchor" href="#recapitulacion-cap05"><i class="fas fa-link"></i></a>
</h2>
<p>Este capítulo ha cerrado el bloque bidimensional. Hemos pasado de comprobar <em>si</em> dos variables se relacionan a describir <em>cómo</em> y <em>cuánto</em>. Como equipaje mínimo llevaremos:</p>
<ul>
<li>La regresión propone una función matemática <span class="math inline">\(\hat{y}_i = f(x_i)\)</span> que aproxima <span class="math inline">\(Y\)</span> a partir de <span class="math inline">\(X\)</span>, con residuos <span class="math inline">\(e_{ij} = y_j - \hat{y}_i\)</span>. La descomposición <span class="math inline">\(y_j = \hat{y}_i + e_{ij}\)</span> es la fórmula fundamental del capítulo.</li>
<li>Hay <strong>dos caminos</strong> clásicos: la regresión <strong>de tipo I</strong> (medias condicionadas, sin forma funcional impuesta) y la regresión <strong>de tipo II</strong> (una forma funcional elegida y estimada por mínimos cuadrados). La segunda es la traducción analítica operativa de la primera; ambas viven en el marco descriptivo del capítulo.</li>
<li>La estimación por <strong>mínimos cuadrados</strong> elige los parámetros que minimizan <span class="math inline">\(\sum e_{ij}^{\,2}\, n_{ij}\)</span>. Es sensible a valores atípicos: un solo caso extremo puede alterar sustancialmente la recta y hundir el <span class="math inline">\(R^{2}\)</span>.</li>
<li>En el <strong>caso lineal</strong> <span class="math inline">\(\hat{y}_i = a + b\, x_i\)</span>, las fórmulas son <span class="math inline">\(\hat{b} = S_{xy}/S_x^{\,2}\)</span> y <span class="math inline">\(\hat{a} = \overline{y} - \hat{b}\, \overline{x}\)</span>. La recta pasa siempre por el centro de gravedad de la nube.</li>
<li>Sobre la misma nube conviven <strong>dos rectas de regresión</strong>: la de <span class="math inline">\(Y\)</span> sobre <span class="math inline">\(X\)</span> y la de <span class="math inline">\(X\)</span> sobre <span class="math inline">\(Y\)</span>, con pendientes <span class="math inline">\(\hat{b}\)</span> y <span class="math inline">\(\hat{b}'\)</span>. Se cruzan en el centro de gravedad y su producto es exactamente el coeficiente de determinación: <span class="math inline">\(\hat{b}\cdot\hat{b}' = R^{2}\)</span>.</li>
<li>La <strong>bondad del ajuste</strong> se mide con el <strong>coeficiente de determinación</strong> <span class="math inline">\(R^{2} = S_{\hat{y}}^{\,2}/S_y^{\,2} = 1 - S_e^{\,2}/S_y^{\,2}\)</span>, comprendido entre <span class="math inline">\(0\)</span> y <span class="math inline">\(1\)</span> y leído como proporción de varianza de <span class="math inline">\(Y\)</span> recogida por la regresión. Un <span class="math inline">\(R^{2}\)</span> resume, pero no diagnostica: <strong>el cuarteto de Anscombe</strong> enseña que cuatro nubes muy distintas pueden compartir el mismo <span class="math inline">\(R^{2}\)</span>. <strong>Los residuos</strong> son la herramienta que dice dónde falla el modelo.</li>
<li>Con la forma funcional dada por buena, la <strong>intensidad</strong> de la relación se mide con el <strong>coeficiente de correlación lineal</strong> <span class="math inline">\(R = S_{xy}/(S_x\cdot S_y)\)</span>, entre <span class="math inline">\(-1\)</span> y <span class="math inline">\(+1\)</span>. El signo indica el sentido de la relación; el valor absoluto, su intensidad.</li>
<li>
<strong>Correlación no es causalidad.</strong> Un <span class="math inline">\(R\)</span> elevado señala coincidencias sistemáticas de comportamiento; identificar relaciones causales exige un modelo teórico y un diseño de investigación específicos.</li>
<li>Muchas relaciones no lineales son <strong>linealizables</strong>: transformando los valores (típicamente con logaritmos) se accede a un ajuste lineal excelente que, al deshacer la transformación, entrega una regresión no lineal.</li>
<li>La <strong>regresión múltiple</strong> generaliza el planteamiento cuando hay varias variables explicativas. Su ejemplo en la flota (añadir la identidad del astillero elevó el <span class="math inline">\(R^{2}\)</span> del <span class="math inline">\(39\,\%\)</span> al <span class="math inline">\(71\,\%\)</span>) muestra que el diagnóstico de residuos suele apuntar directamente a la variable que falta. El <strong><span class="math inline">\(R^{2}\)</span> ajustado</strong> corrige el sesgo del <span class="math inline">\(R^{2}\)</span> ordinario a favor de los modelos con más variables.</li>
</ul>
<p>Con esto damos por cerrado el bloque de estadística descriptiva bidimensional. El siguiente bloque del curso da un giro conceptual: dejamos por un tiempo el análisis de datos observados y entramos en el terreno de la <strong>probabilidad</strong>, la herramienta que permitirá, más adelante, transformar todas estas descripciones en instrumentos de <strong>inferencia</strong> sobre poblaciones. Cuando volvamos a los datos, ya no serán solo los que tenemos delante: serán una ventana estadísticamente honesta a lo que ocurre en el universo del que provienen.</p>
</div>
<div id="problemas-cap05" class="section level2" number="5.7">
<h2>
<span class="header-section-number">5.7</span> Problemas propuestos.<a class="anchor" aria-label="anchor" href="#problemas-cap05"><i class="fas fa-link"></i></a>
</h2>
<p>Los ejercicios que siguen combinan <strong>cálculo controlado</strong> —fórmulas MCO sobre datos pequeños, verificación de la identidad <span class="math inline">\(\hat{b}\cdot\hat{b}' = R^2\)</span>, linealización log-log— con un peso importante de <strong>interpretación</strong>: qué significa la pendiente en unidades del problema, cuándo una predicción cae fuera del rango razonable, qué revela un <span class="math inline">\(R^2\)</span> modesto, y cómo detectar una variable acechante detrás de una regresión simple aparentemente convincente. Todas las soluciones detalladas se recogen al final del capítulo.</p>
<div id="problema-5.1.-leer-una-recta-ya-ajustada." class="section level3" number="5.7.1">
<h3>
<span class="header-section-number">5.7.1</span> Problema 5.1. Leer una recta ya ajustada.<a class="anchor" aria-label="anchor" href="#problema-5.1.-leer-una-recta-ya-ajustada."><i class="fas fa-link"></i></a>
</h3>
<p><strong>Sagan Olbers</strong> ha ajustado, sobre las 300 compañías R-Stars, la recta de regresión de la <strong>facturación anual</strong> (<span class="math inline">\(Y\)</span>, en millones de PAVOs) sobre el <strong>número de rutas activas</strong> (<span class="math inline">\(X\)</span>):</p>
<p><span class="math display">\[\hat{y} \;=\; 12{,}4 \;+\; 3{,}8\cdot x, \qquad R^{2} \;=\; 0{,}78.\]</span></p>
<p>El número de rutas de las compañías del fichero oscila entre <strong>1 y 25</strong>.</p>
<p>Se pide:</p>
<ol style="list-style-type: lower-alpha">
<li>Interpreta económicamente los coeficientes <span class="math inline">\(\hat{a} = 12{,}4\)</span> y <span class="math inline">\(\hat{b} = 3{,}8\)</span>. ¿Tiene sentido literal el término independiente en este contexto?</li>
<li>Interpreta el coeficiente de determinación <span class="math inline">\(R^{2} = 0{,}78\)</span>.</li>
<li>La CEO de una compañía con <strong>8 rutas activas</strong> quiere saber cuál sería la facturación esperada según el modelo. Aplícalo.</li>
<li>Un consultor sugiere aplicar la recta para estimar la facturación esperada de una compañía con <strong>60 rutas activas</strong>. ¿Es una predicción defendible? Justifica.</li>
</ol>
</div>
<div id="problema-5.2.-calcular-la-recta-desde-cero." class="section level3" number="5.7.2">
<h3>
<span class="header-section-number">5.7.2</span> Problema 5.2. Calcular la recta desde cero.<a class="anchor" aria-label="anchor" href="#problema-5.2.-calcular-la-recta-desde-cero."><i class="fas fa-link"></i></a>
</h3>
<p><strong>Xelia Bluebird</strong> dispone de datos sobre 5 compañías del sector, con la <strong>inversión anual en digitalización</strong> (<span class="math inline">\(X\)</span>, en miles de PAVOs) y el <strong>margen operativo</strong> (<span class="math inline">\(Y\)</span>, en %):</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="center">Compañía</th>
<th align="center"><span class="math inline">\(x_i\)</span></th>
<th align="center"><span class="math inline">\(y_i\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center">C-01</td>
<td align="center">2</td>
<td align="center">40</td>
</tr>
<tr class="even">
<td align="center">C-02</td>
<td align="center">4</td>
<td align="center">45</td>
</tr>
<tr class="odd">
<td align="center">C-03</td>
<td align="center">6</td>
<td align="center">55</td>
</tr>
<tr class="even">
<td align="center">C-04</td>
<td align="center">8</td>
<td align="center">60</td>
</tr>
<tr class="odd">
<td align="center">C-05</td>
<td align="center">10</td>
<td align="center">70</td>
</tr>
</tbody>
</table></div>
<div style="text-align: center;">
<p><strong>Tabla 5.3</strong></p>
</div>
<p>Se pide:</p>
<ol style="list-style-type: lower-alpha">
<li>Calcula las medias <span class="math inline">\(\overline{x}\)</span> y <span class="math inline">\(\overline{y}\)</span>.</li>
<li>Calcula la varianza de <span class="math inline">\(X\)</span> y la covarianza <span class="math inline">\(S_{xy}\)</span>.</li>
<li>Aplica las fórmulas mínimo-cuadráticas y escribe la ecuación de la recta <span class="math inline">\(\hat{y} = \hat{a} + \hat{b}\, x\)</span>.</li>
<li>Interpreta económicamente los coeficientes obtenidos. ¿Qué margen operativo predice el modelo para una compañía con <strong>5 mil PAVOs</strong> de inversión digital?</li>
</ol>
</div>
<div id="problema-5.3.-predicción-y-extrapolación-en-la-flota." class="section level3" number="5.7.3">
<h3>
<span class="header-section-number">5.7.3</span> Problema 5.3. Predicción y extrapolación en la flota.<a class="anchor" aria-label="anchor" href="#problema-5.3.-predicci%C3%B3n-y-extrapolaci%C3%B3n-en-la-flota."><i class="fas fa-link"></i></a>
</h3>
<p>Un analista de la ARTI ha ajustado, sobre datos de cargueros cuya antigüedad oscila entre <strong>2 y 25 años</strong>, la recta que predice el <strong>tonelaje</strong> de una nave a partir de su antigüedad:</p>
<p><span class="math display">\[\hat{y} \;=\; 628 \;+\; 11{,}6\cdot x, \qquad R^{2} \;=\; 0{,}38.\]</span></p>
<p>(tonelaje en miles de toneladas, antigüedad en años.)</p>
<p>Se pide, para cada uno de los siguientes usos del modelo:</p>
<ol style="list-style-type: lower-alpha">
<li>Predecir el tonelaje de un carguero con <strong>8 años</strong> de antigüedad. ¿Es una predicción defendible?</li>
<li>Predecir el tonelaje de un carguero <strong>recién estrenado</strong> (<span class="math inline">\(x = 0\)</span>). ¿Es defendible en este caso?</li>
<li>Predecir el tonelaje de un <strong>carguero experimental de 40 años</strong> (<span class="math inline">\(x = 40\)</span>). ¿Es defendible?</li>
<li>La ARTI encarga una predicción <strong>individualizada</strong> del tonelaje de un carguero concreto de 8 años matriculado en Mustafar. ¿Es la recta un instrumento adecuado para responder? Justifica.</li>
</ol>
</div>
<div id="problema-5.4.-el-efecto-de-un-outlier-sobre-la-recta." class="section level3" number="5.7.4">
<h3>
<span class="header-section-number">5.7.4</span> Problema 5.4. El efecto de un <em>outlier</em> sobre la recta.<a class="anchor" aria-label="anchor" href="#problema-5.4.-el-efecto-de-un-outlier-sobre-la-recta."><i class="fas fa-link"></i></a>
</h3>
<p>Un analista ha ajustado una recta sobre 30 cargueros de una serie regular de <em>Selene Dynamics</em>. Después incorpora al análisis un <strong>prototipo experimental</strong> de <em>Wraith Industries</em>, extremadamente ligero pese a llevar 15 años en servicio. Los coeficientes obtenidos antes y después de añadir el prototipo son:</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left"></th>
<th align="center">Sin prototipo</th>
<th align="center">Con prototipo</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Ordenada <span class="math inline">\(\hat{a}\)</span>
</td>
<td align="center">30,0</td>
<td align="center">45,0</td>
</tr>
<tr class="even">
<td align="left">Pendiente <span class="math inline">\(\hat{b}\)</span>
</td>
<td align="center">8,0</td>
<td align="center">3,5</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(R^{2}\)</span></td>
<td align="center">0,83</td>
<td align="center">0,26</td>
</tr>
<tr class="even">
<td align="left">Correlación <span class="math inline">\(R\)</span>
</td>
<td align="center">0,91</td>
<td align="center">0,51</td>
</tr>
</tbody>
</table></div>
<div style="text-align: center;">
<p><strong>Tabla 5.4</strong></p>
</div>
<p>Se pide:</p>
<ol style="list-style-type: lower-alpha">
<li>¿Qué coeficientes se han visto más afectados por la incorporación del prototipo? ¿Cómo interpretas ese cambio?</li>
<li>¿Por qué el <span class="math inline">\(R^{2}\)</span> se hunde de manera tan drástica al añadir una sola observación entre treinta?</li>
<li>La recta con prototipo asigna a un carguero de 15 años una previsión de tonelaje muy distinta a la que le asignaría la recta sin él. ¿Cuál de las dos rectas es la más defendible como <em>“recta representativa del comportamiento habitual de la flota”</em>?</li>
<li>A la vista del efecto observado, ¿cuál debería ser la primera decisión analítica antes de dar por bueno el modelo?</li>
</ol>
</div>
<div id="problema-5.5.-regresión-de-tipo-i-y-tipo-ii-sobre-la-misma-tabla." class="section level3" number="5.7.5">
<h3>
<span class="header-section-number">5.7.5</span> Problema 5.5. Regresión de tipo I y tipo II sobre la misma tabla.<a class="anchor" aria-label="anchor" href="#problema-5.5.-regresi%C3%B3n-de-tipo-i-y-tipo-ii-sobre-la-misma-tabla."><i class="fas fa-link"></i></a>
</h3>
<p>Sobre 60 cargueros de un cierto sector se ha construido una tabla de correlación entre <strong>años en servicio</strong> (<span class="math inline">\(X\)</span>) y <strong>coste medio de mantenimiento anual</strong> (<span class="math inline">\(Y\)</span>, en miles de PAVOs). Las medias condicionadas del coste dentro de cada intervalo de antigüedad son:</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="26%">
<col width="15%">
<col width="19%">
<col width="37%">
</colgroup>
<thead><tr class="header">
<th align="center">Intervalo antigüedad</th>
<th align="center">Marca <span class="math inline">\(x_i\)</span>
</th>
<th align="center"><span class="math inline">\(n_{i\bullet}\)</span></th>
<th align="center"><span class="math inline">\(\overline{y}_{\,\mid\, x_i}\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center">(0, 5]</td>
<td align="center">2,5</td>
<td align="center">12</td>
<td align="center">20</td>
</tr>
<tr class="even">
<td align="center">(5, 10]</td>
<td align="center">7,5</td>
<td align="center">15</td>
<td align="center">22</td>
</tr>
<tr class="odd">
<td align="center">(10, 15]</td>
<td align="center">12,5</td>
<td align="center">18</td>
<td align="center">25</td>
</tr>
<tr class="even">
<td align="center">(15, 20]</td>
<td align="center">17,5</td>
<td align="center">10</td>
<td align="center">40</td>
</tr>
<tr class="odd">
<td align="center">(20, 30]</td>
<td align="center">25</td>
<td align="center">5</td>
<td align="center">70</td>
</tr>
</tbody>
</table></div>
<div style="text-align: center;">
<p><strong>Tabla 5.5</strong></p>
</div>
<p>Sobre los mismos datos se ha ajustado, por MCO, la recta <span class="math inline">\(\hat{y} = 5 + 2{,}0\cdot x\)</span> con <span class="math inline">\(R^{2} = 0{,}48\)</span>.</p>
<p>Se pide:</p>
<ol style="list-style-type: lower-alpha">
<li>Dibuja mentalmente (o esquemáticamente) los cinco puntos <span class="math inline">\((x_i,\, \overline{y}_{\,\mid\, x_i})\)</span> que constituyen la <strong>regresión de tipo I</strong>. ¿Sugieren un comportamiento lineal, o hay algún salto?</li>
<li>¿Es coherente el <span class="math inline">\(R^{2} = 0{,}48\)</span> con la comparación visual entre las medias condicionadas y la recta MCO?</li>
<li>¿Qué forma funcional del capítulo podría capturar mejor este patrón que una recta simple?</li>
<li>¿Qué conclusión de gestión extrae el responsable de mantenimiento al ver estas medias condicionadas: <em>“el mantenimiento crece linealmente con la antigüedad”</em> o <em>“hay un umbral crítico a partir del cual el coste se dispara”</em>?</li>
</ol>
</div>
<div id="problema-5.6.-descomposición-de-la-varianza." class="section level3" number="5.7.6">
<h3>
<span class="header-section-number">5.7.6</span> Problema 5.6. Descomposición de la varianza.<a class="anchor" aria-label="anchor" href="#problema-5.6.-descomposici%C3%B3n-de-la-varianza."><i class="fas fa-link"></i></a>
</h3>
<p>De un ajuste lineal sobre 200 compañías se conocen los siguientes valores:</p>
<ul>
<li>Varianza total de <span class="math inline">\(Y\)</span>: <span class="math inline">\(S_y^{\,2} = 100\)</span>.</li>
<li>Varianza residual: <span class="math inline">\(S_e^{\,2} = 25\)</span>.</li>
</ul>
<p>Se pide:</p>
<ol style="list-style-type: lower-alpha">
<li>Calcula la varianza explicada <span class="math inline">\(S_{\hat{y}}^{\,2}\)</span>.</li>
<li>Calcula el coeficiente de determinación <span class="math inline">\(R^{2}\)</span>.</li>
<li>Interpreta el resultado en clave de bondad del ajuste.</li>
<li>Si un directivo pregunta <em>“¿qué proporción de la variabilidad de <span class="math inline">\(Y\)</span> queda sin explicar por la regresión?”</em>, ¿qué respuesta le das y cómo la derivas de los datos anteriores?</li>
</ol>
</div>
<div id="problema-5.7.-comparar-cuatro-regresiones-por-su-r2." class="section level3" number="5.7.7">
<h3>
<span class="header-section-number">5.7.7</span> Problema 5.7. Comparar cuatro regresiones por su <span class="math inline">\(R^{2}\)</span>.<a class="anchor" aria-label="anchor" href="#problema-5.7.-comparar-cuatro-regresiones-por-su-r2."><i class="fas fa-link"></i></a>
</h3>
<p><strong>Sagan Olbers</strong> ha ajustado, sobre las 300 compañías R-Stars, cuatro regresiones lineales simples con distintas variables explicativas para predecir la <strong>rentabilidad anual</strong> (<span class="math inline">\(Y\)</span>, en %):</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">Explicativa (<span class="math inline">\(X\)</span>)</th>
<th align="center"><span class="math inline">\(R^{2}\)</span></th>
<th align="center"><span class="math inline">\(R\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Ingresos totales</td>
<td align="center">0,08</td>
<td align="center">+0,28</td>
</tr>
<tr class="even">
<td align="left">Índice de digitalización</td>
<td align="center">0,45</td>
<td align="center">+0,67</td>
</tr>
<tr class="odd">
<td align="left">Antigüedad media de la flota</td>
<td align="center">0,12</td>
<td align="center">-0,35</td>
</tr>
<tr class="even">
<td align="left">Tamaño de la flota (nº de cargueros)</td>
<td align="center">0,03</td>
<td align="center">+0,17</td>
</tr>
</tbody>
</table></div>
<div style="text-align: center;">
<p><strong>Tabla 5.6</strong></p>
</div>
<p>Se pide:</p>
<ol style="list-style-type: lower-alpha">
<li>Clasifica las cuatro asociaciones por intensidad, según la escala orientativa del capítulo.</li>
<li>¿Qué signos tienen las relaciones y qué te dicen sobre el sector?</li>
<li>Si tuvieras que <strong>elegir una única variable</strong> explicativa para incluir en un modelo simple de rentabilidad, ¿cuál elegirías? Justifica.</li>
<li>¿Puede afirmarse, a la vista de estos <span class="math inline">\(R^{2}\)</span>, que <em>la digitalización causa mayor rentabilidad</em>? Justifica.</li>
</ol>
</div>
<div id="problema-5.8.-cuarteto-de-anscombe-en-clave-r-stars." class="section level3" number="5.7.8">
<h3>
<span class="header-section-number">5.7.8</span> Problema 5.8. Cuarteto de Anscombe en clave R-Stars.<a class="anchor" aria-label="anchor" href="#problema-5.8.-cuarteto-de-anscombe-en-clave-r-stars."><i class="fas fa-link"></i></a>
</h3>
<p>Cuatro conjuntos de datos —cada uno con 11 cargueros— presentan estos descriptivos <strong>idénticos</strong>:</p>
<ul>
<li>
<span class="math inline">\(\overline{x} = 9\)</span>; <span class="math inline">\(\overline{y} = 7{,}5\)</span>.</li>
<li>Recta ajustada: <span class="math inline">\(\hat{y} = 3 + 0{,}5\cdot x\)</span>.</li>
<li>
<span class="math inline">\(R^{2} = 0{,}67\)</span>; <span class="math inline">\(R = 0{,}82\)</span>.</li>
</ul>
<p>Sin embargo, al examinar los diagramas de dispersión, un analista describe cuatro estructuras muy distintas:</p>
<ul>
<li>
<strong>Nube (I).</strong> Puntos dispersos alrededor de la recta, sin patrón sistemático.</li>
<li>
<strong>Nube (II).</strong> Patrón claramente <strong>curvo</strong> (parabólico), en forma de arco.</li>
<li>
<strong>Nube (III).</strong> 10 puntos alineados casi perfectamente sobre una recta y <strong>un solo punto muy separado</strong> del patrón (<em>outlier</em> vertical).</li>
<li>
<strong>Nube (IV).</strong> Todos los cargueros tienen la misma antigüedad excepto uno, cuya antigüedad muy distinta arrastra por sí sola toda la pendiente (<strong>punto de alta palanca</strong>).</li>
</ul>
<p>Se pide:</p>
<ol style="list-style-type: lower-alpha">
<li>¿En cuál de las cuatro nubes la recta <span class="math inline">\(\hat{y} = 3 + 0{,}5\, x\)</span> es un resumen <strong>honesto</strong> de la relación?</li>
<li>Para cada una de las otras tres nubes, ¿qué acción emprenderías <strong>antes</strong> de reportar el modelo?</li>
<li>¿Qué moraleja del capítulo ilustra este cuarteto sobre el uso del <span class="math inline">\(R^{2}\)</span> y de los coeficientes de la recta?</li>
<li>Si el <span class="math inline">\(R^{2}\)</span> y los coeficientes son idénticos en las cuatro nubes, ¿qué herramienta —barata y rápida— permite distinguirlas?</li>
</ol>
</div>
<div id="problema-5.9.-las-dos-rectas-y-r2." class="section level3" number="5.7.9">
<h3>
<span class="header-section-number">5.7.9</span> Problema 5.9. Las dos rectas y <span class="math inline">\(R^{2}\)</span>.<a class="anchor" aria-label="anchor" href="#problema-5.9.-las-dos-rectas-y-r2."><i class="fas fa-link"></i></a>
</h3>
<p>Sobre un cruce de dos variables cuantitativas en 100 compañías del sector se conocen los siguientes momentos:</p>
<ul>
<li>
<span class="math inline">\(\overline{x} = 20\)</span>; <span class="math inline">\(\overline{y} = 50\)</span>.</li>
<li>
<span class="math inline">\(S_x^{\,2} = 4\)</span>; <span class="math inline">\(S_y^{\,2} = 9\)</span>; <span class="math inline">\(S_{xy} = 3\)</span>.</li>
</ul>
<p>Se pide:</p>
<ol style="list-style-type: lower-alpha">
<li>Calcula la pendiente y la ordenada de la recta de regresión de <span class="math inline">\(Y\)</span> sobre <span class="math inline">\(X\)</span>.</li>
<li>Calcula la pendiente y la ordenada de la recta de regresión de <span class="math inline">\(X\)</span> sobre <span class="math inline">\(Y\)</span>.</li>
<li>Calcula el coeficiente de determinación por <strong>dos vías</strong>: mediante <span class="math inline">\(R^{2} = S_{xy}^{\,2}/(S_x^{\,2}\cdot S_y^{\,2})\)</span> y mediante <span class="math inline">\(\hat{b}\cdot \hat{b}'\)</span>. Comprueba que coinciden.</li>
<li>Calcula el coeficiente de correlación <span class="math inline">\(R\)</span> e interprétalo. Describe cualitativamente cómo se abren las dos rectas en torno al punto <span class="math inline">\((\overline{x}, \overline{y})\)</span>.</li>
</ol>
</div>
<div id="problema-5.10.-interpretar-coeficientes-de-correlación." class="section level3" number="5.7.10">
<h3>
<span class="header-section-number">5.7.10</span> Problema 5.10. Interpretar coeficientes de correlación.<a class="anchor" aria-label="anchor" href="#problema-5.10.-interpretar-coeficientes-de-correlaci%C3%B3n."><i class="fas fa-link"></i></a>
</h3>
<p>La AITM ha calculado los siguientes coeficientes de correlación lineal <span class="math inline">\(R\)</span> entre pares de variables sobre las 300 compañías R-Stars:</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">Cruce</th>
<th align="center"><span class="math inline">\(R\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Ingresos × Costos operativos</td>
<td align="center">+0,96</td>
</tr>
<tr class="even">
<td align="left">Rentabilidad × Índice de digitalización</td>
<td align="center">+0,67</td>
</tr>
<tr class="odd">
<td align="left">Antigüedad flota × Índice de digitalización</td>
<td align="center">-0,45</td>
</tr>
<tr class="even">
<td align="left">Nº de rutas × Nº de tripulantes</td>
<td align="center">+0,88</td>
</tr>
<tr class="odd">
<td align="left">Gasto en cantina × Distancia al sistema Klendathu</td>
<td align="center">-0,03</td>
</tr>
</tbody>
</table></div>
<div style="text-align: center;">
<p><strong>Tabla 5.7</strong></p>
</div>
<p>Se pide:</p>
<ol style="list-style-type: lower-alpha">
<li>Clasifica cada relación por <strong>intensidad</strong> y <strong>signo</strong>, según la escala del capítulo.</li>
<li>¿Cuál es la relación más <em>“casi determinista”</em> del sector, y qué explicación económica sugieres?</li>
<li>La relación <strong>negativa</strong> entre antigüedad de la flota e índice de digitalización, ¿te sorprende? Explica.</li>
<li>Un directivo lee las cifras y concluye: <em>“digitalizar la compañía causa un aumento de la rentabilidad en 0,67 puntos por cada punto de índice.”</em> ¿Qué <strong>dos errores</strong> contiene esa afirmación?</li>
</ol>
</div>
<div id="problema-5.11.-correlación-y-causalidad-segunda-vuelta." class="section level3" number="5.7.11">
<h3>
<span class="header-section-number">5.7.11</span> Problema 5.11. Correlación y causalidad (segunda vuelta).<a class="anchor" aria-label="anchor" href="#problema-5.11.-correlaci%C3%B3n-y-causalidad-segunda-vuelta."><i class="fas fa-link"></i></a>
</h3>
<p>Un estudio del sector R-Stars publica el siguiente titular:</p>
<blockquote>
<p><em>“El tamaño de la flota está fuertemente correlacionado con la rentabilidad de las compañías (<span class="math inline">\(R = +0{,}72\)</span>). Las compañías que aumenten su flota serán más rentables.”</em></p>
</blockquote>
<p>Se pide:</p>
<ol style="list-style-type: lower-alpha">
<li>La segunda frase del titular, ¿es una conclusión legítima a partir de la primera? Justifica.</li>
<li>Propón al menos <strong>dos</strong> hipótesis alternativas —causales o no— que puedan explicar la asociación observada entre tamaño de flota y rentabilidad.</li>
<li>Cita una <strong>tercera variable</strong> que pueda estar detrás de la asociación (factor de confusión), y explica su rol.</li>
<li>Un analista consciente del problema añade a la regresión otras variables (galaxia de operación, antigüedad, forma jurídica) y comprueba que el efecto de <em>“tamaño de flota”</em> sobre rentabilidad <strong>se reduce mucho</strong>. ¿Qué te sugiere ese hallazgo sobre la relación causal original?</li>
</ol>
</div>
<div id="problema-5.12.-linealización-curva-de-aprendizaje-en-enterprise-logistics." class="section level3" number="5.7.12">
<h3>
<span class="header-section-number">5.7.12</span> Problema 5.12. Linealización: curva de aprendizaje en <em>Enterprise Logistics</em>.<a class="anchor" aria-label="anchor" href="#problema-5.12.-linealizaci%C3%B3n-curva-de-aprendizaje-en-enterprise-logistics."><i class="fas fa-link"></i></a>
</h3>
<p>Un aprendiz de piloto en la escuela de <em>Enterprise Logistics</em> cronometra el tiempo (en minutos) que tarda en completar una maniobra estándar de acoplamiento a medida que acumula operaciones. Los datos son:</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="center">Operaciones acumuladas (<span class="math inline">\(x_i\)</span>)</th>
<th align="center">1</th>
<th align="center">2</th>
<th align="center">4</th>
<th align="center">8</th>
<th align="center">16</th>
</tr></thead>
<tbody><tr class="odd">
<td align="center">Tiempo por maniobra (<span class="math inline">\(y_i\)</span>, min)</td>
<td align="center">60</td>
<td align="center">42</td>
<td align="center">30</td>
<td align="center">21</td>
<td align="center">15</td>
</tr></tbody>
</table></div>
<div style="text-align: center;">
<p><strong>Tabla 5.8</strong></p>
</div>
<p>Un ajuste directo por MCO da <span class="math inline">\(\hat{y} = 46{,}2 - 2{,}1\cdot x\)</span> con <span class="math inline">\(R^{2} = 0{,}70\)</span>: modesto, y con residuos que muestran patrón sistemático (curvatura no capturada).</p>
<p>Se propone entonces una regresión potencial <span class="math inline">\(\hat{y} = a\cdot x^{b}\)</span>. Tras aplicar logaritmos naturales a ambas variables se han calculado:</p>
<ul>
<li>
<span class="math inline">\(\overline{\log x} = 1{,}386\)</span>; <span class="math inline">\(\overline{\log y} = 3{,}396\)</span>.</li>
<li>
<span class="math inline">\(S^{2}_{\log x} = 0{,}961\)</span>; <span class="math inline">\(S_{\log x,\ \log y} = -0{,}476\)</span>.</li>
<li>
<span class="math inline">\(R^{2}_{\log} = 0{,}9995\)</span>.</li>
</ul>
<p>Se pide:</p>
<ol style="list-style-type: lower-alpha">
<li>Calcula la pendiente <span class="math inline">\(b_{\log}\)</span> del ajuste lineal sobre las variables transformadas (<span class="math inline">\(\log y\)</span> sobre <span class="math inline">\(\log x\)</span>).</li>
<li>Calcula la ordenada <span class="math inline">\(\log a\)</span> del ajuste lineal transformado y, deshaciendo la transformación, el parámetro <span class="math inline">\(a\)</span> del modelo potencial (recuerda: <span class="math inline">\(a = e^{\log a}\)</span>).</li>
<li>Escribe la ecuación del modelo potencial. Interpreta el <strong>signo</strong> y la <strong>magnitud</strong> del exponente <span class="math inline">\(b\)</span>.</li>
<li>Un jefe de estudios afirma: <em>“Cada vez que el aprendiz duplica sus operaciones acumuladas, su tiempo por maniobra se reduce, aproximadamente, en un tercio.”</em> ¿Es coherente esa afirmación con el exponente obtenido? (Recuerda: la reducción al duplicar <span class="math inline">\(x\)</span> es <span class="math inline">\(1 - 2^{b}\)</span>.)</li>
</ol>
</div>
<div id="problema-5.13.-ejercicio-integrador-la-variable-acechante-en-la-flota." class="section level3" number="5.7.13">
<h3>
<span class="header-section-number">5.7.13</span> Problema 5.13. Ejercicio integrador: la variable acechante en la flota.<a class="anchor" aria-label="anchor" href="#problema-5.13.-ejercicio-integrador-la-variable-acechante-en-la-flota."><i class="fas fa-link"></i></a>
</h3>
<p>Un analista ha ajustado dos regresiones sobre los 48 cargueros del sector R-Stars, con el <strong>tonelaje</strong> (<span class="math inline">\(Y\)</span>, miles de toneladas) como variable explicada:</p>
<p><strong>Modelo A</strong> — regresión simple con solo la antigüedad:</p>
<p><span class="math display">\[\hat{y} \;=\; 628 \;+\; 12{,}6\cdot \text{ANTIG}, \qquad R^{2} \;=\; 0{,}39.\]</span></p>
<p><strong>Modelo B</strong> — regresión múltiple con antigüedad y astillero (con ARCTURUS como categoría de referencia; <span class="math inline">\(D_K = 1\)</span> si el carguero es de KORRIGAN, <span class="math inline">\(D_S = 1\)</span> si es de SELENE):</p>
<p><span class="math display">\[\hat{y} \;=\; 722 \;+\; 1{,}44\cdot \text{ANTIG} \;+\; 107\cdot D_K \;-\; 111\cdot D_S, \qquad R^{2} \;=\; 0{,}71,\ R^{2}_{\text{aj}} \;=\; 0{,}69.\]</span></p>
<p>Se pide:</p>
<ol style="list-style-type: lower-alpha">
<li>Interpreta el paso del <span class="math inline">\(R^{2}\)</span> del Modelo A (0,39) al <span class="math inline">\(R^{2}\)</span> del Modelo B (0,71). ¿Qué proporción <strong>adicional</strong> de la variabilidad del tonelaje ha quedado explicada al incluir el astillero?</li>
<li>La pendiente de la antigüedad pasa de <strong>12,6</strong> (Modelo A) a <strong>1,44</strong> (Modelo B). ¿Por qué se reduce tanto? ¿Qué te dice ese cambio sobre lo que estaba “escondido” en el efecto de la antigüedad del modelo simple?</li>
<li>Interpreta los coeficientes de las <em>dummies</em>: un carguero de <strong>KORRIGAN</strong>, ¿es en promedio más o menos pesado que uno equivalente de ARCTURUS? ¿Y uno de <strong>SELENE</strong>?</li>
<li>¿Por qué reportamos el <strong><span class="math inline">\(R^{2}\)</span> ajustado</strong> en el modelo múltiple pero no en el simple?</li>
<li>¿Cómo se llama, en el vocabulario del capítulo (o del anterior), el fenómeno por el que una variable oculta —aquí, el astillero— altera la interpretación de la pendiente de la variable explícita —aquí, la antigüedad— cuando no se incluye en el modelo?</li>
</ol>
</div>
</div>
<div id="soluciones-cap05" class="section level2" number="5.8">
<h2>
<span class="header-section-number">5.8</span> Soluciones a los problemas propuestos.<a class="anchor" aria-label="anchor" href="#soluciones-cap05"><i class="fas fa-link"></i></a>
</h2>
<div id="solución-al-problema-5.1." class="section level3" number="5.8.1">
<h3>
<span class="header-section-number">5.8.1</span> Solución al Problema 5.1.<a class="anchor" aria-label="anchor" href="#soluci%C3%B3n-al-problema-5.1."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: lower-alpha">
<li>
<p><span class="math inline">\(\hat{a} = 12{,}4\)</span>: valor que la recta asigna a la facturación cuando el número de rutas es cero. <strong>No tiene sentido literal</strong>: una compañía sin rutas no factura. Como suele ocurrir con el término independiente, es un parámetro de ajuste que ancla la recta, no un valor económico interpretable por sí mismo.</p>
<p><span class="math inline">\(\hat{b} = 3{,}8\)</span>: por cada <strong>ruta adicional</strong>, la facturación esperada aumenta, en promedio, en <strong>3,8 millones de PAVOs</strong>. Es la lectura útil del modelo, y viene ya expresada en unidades del problema (millones de PAVOs por ruta).</p>
</li>
<li><p>El <span class="math inline">\(R^{2} = 0{,}78\)</span> significa que el <strong>78%</strong> de la variabilidad de la facturación entre las 300 compañías queda explicada por la recta ajustada sobre el número de rutas. Es un ajuste <strong>fuerte</strong>: el número de rutas es, por sí solo, un predictor muy informativo de la facturación.</p></li>
<li><p><span class="math inline">\(\hat{y}(8) = 12{,}4 + 3{,}8\cdot 8 = 12{,}4 + 30{,}4 = \mathbf{42{,}8}\)</span> millones de PAVOs.</p></li>
<li><p><strong>No es defendible.</strong> El rango observado va de 1 a 25 rutas; <span class="math inline">\(x = 60\)</span> está muy por encima del máximo del fichero. Fuera de ese rango, la recta pierde toda garantía: podría no cumplirse la linealidad (rendimientos decrecientes por saturación de mercado, por ejemplo), o directamente el régimen del negocio ser distinto para operadores intergalácticos de gran escala. Aplicar la fórmula a 60 no es hacer una previsión: es hacer un acto de fe.</p></li>
</ol>
</div>
<div id="solución-al-problema-5.2." class="section level3" number="5.8.2">
<h3>
<span class="header-section-number">5.8.2</span> Solución al Problema 5.2.<a class="anchor" aria-label="anchor" href="#soluci%C3%B3n-al-problema-5.2."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: lower-alpha">
<li><p><span class="math inline">\(\overline{x} = (2+4+6+8+10)/5 = 30/5 = \mathbf{6}\)</span>. <span class="math inline">\(\overline{y} = (40+45+55+60+70)/5 = 270/5 = \mathbf{54}\)</span>.</p></li>
<li>
<p>Momento respecto al origen:</p>
<ul>
<li>
<span class="math inline">\(a_{20} = (4+16+36+64+100)/5 = 220/5 = 44 \Rightarrow S_x^{\,2} = 44 - 6^{2} = \mathbf{8}\)</span>.</li>
<li>
<span class="math inline">\(a_{11} = (2\cdot 40 + 4\cdot 45 + 6\cdot 55 + 8\cdot 60 + 10\cdot 70)/5 = (80+180+330+480+700)/5 = 1\,770/5 = 354\)</span>.</li>
<li>
<span class="math inline">\(S_{xy} = a_{11} - \overline{x}\cdot\overline{y} = 354 - 6\cdot 54 = 354 - 324 = \mathbf{30}\)</span>.</li>
</ul>
</li>
<li>
<p>Aplicando las fórmulas mínimo-cuadráticas:</p>
<p><span class="math display">\[\hat{b} = \dfrac{S_{xy}}{S_x^{\,2}} = \dfrac{30}{8} = \mathbf{3{,}75}; \qquad \hat{a} = \overline{y} - \hat{b}\cdot\overline{x} = 54 - 3{,}75\cdot 6 = 54 - 22{,}5 = \mathbf{31{,}5}.\]</span></p>
<p>Recta: <span class="math inline">\(\boxed{\;\hat{y} = 31{,}5 + 3{,}75\cdot x\;}\)</span>.</p>
</li>
<li>
<p>Interpretación:</p>
<ul>
<li>
<span class="math inline">\(\hat{a} = 31{,}5\)</span>: margen operativo que la recta asigna a una compañía con inversión digital nula. Puede leerse literalmente como el “margen basal” del sector, y en este caso sí tiene un sentido económico razonable (una compañía sin digitalización sigue teniendo margen).</li>
<li>
<span class="math inline">\(\hat{b} = 3{,}75\)</span>: por cada <strong>mil PAVOs adicionales</strong> de inversión en digitalización, el margen operativo aumenta, en promedio, <strong>3,75 puntos porcentuales</strong>.</li>
</ul>
<p>Predicción para <span class="math inline">\(x = 5\)</span> (mil PAVOs): <span class="math inline">\(\hat{y}(5) = 31{,}5 + 3{,}75\cdot 5 = 31{,}5 + 18{,}75 = \mathbf{50{,}25\%}\)</span>.</p>
</li>
</ol>
</div>
<div id="solución-al-problema-5.3." class="section level3" number="5.8.3">
<h3>
<span class="header-section-number">5.8.3</span> Solución al Problema 5.3.<a class="anchor" aria-label="anchor" href="#soluci%C3%B3n-al-problema-5.3."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: lower-alpha">
<li><p><span class="math inline">\(\hat{y}(8) = 628 + 11{,}6\cdot 8 = 628 + 92{,}8 = \mathbf{720{,}8}\)</span> mil toneladas. Es una <strong>predicción defendible</strong>: <span class="math inline">\(x = 8\)</span> está claramente dentro del rango observado (2-25 años).</p></li>
<li><p><span class="math inline">\(\hat{y}(0) = 628\)</span>. Aceptable <strong>con reservas</strong>: <span class="math inline">\(x = 0\)</span> queda justo por debajo del mínimo observado (2). Está muy cerca del rango, pero literalmente fuera. Además, el “carguero recién estrenado” es un caso conceptualmente distinto (nunca ha operado), del que la recta —construida sobre naves con al menos 2 años de servicio— no tiene por qué informar bien. Interpretable como referencia, no como pronóstico firme.</p></li>
<li><p><span class="math inline">\(\hat{y}(40) = 628 + 11{,}6\cdot 40 = 628 + 464 = \mathbf{1\,092}\)</span> mil toneladas. <strong>No defendible</strong>: <span class="math inline">\(x = 40\)</span> está muy por encima del máximo observado (25). Es exactamente el escenario que el capítulo desaconseja: cualquier cambio de régimen (naves de generación anterior, cargueros de museo, cambio de tecnología estructural) rompería la validez de la extrapolación. Además, 1 092 mil toneladas es una cifra sospechosamente alta comparada con el máximo típico del sector.</p></li>
<li>
<p><strong>No</strong> es un instrumento adecuado para una predicción individualizada. Dos razones:</p>
<ul>
<li>La recta predice <strong>promedios</strong>, no individuos. Un carguero concreto puede desviarse notablemente del pronóstico puntual.</li>
<li>Con <span class="math inline">\(R^{2} = 0{,}38\)</span>, más del 60% de la variabilidad del tonelaje queda <strong>sin explicar</strong> por la antigüedad. El residuo típico puede ser muy grande.</li>
</ul>
<p>Para una predicción individual defendible, habría que acompañar la cifra puntual con un intervalo de confianza (que requiere las herramientas del bloque de Inferencia), o incluir otras variables (astillero, tipo de motor, sector de operación) que reduzcan la varianza residual. En este mismo capítulo se ve cómo la regresión múltiple con el astillero incluido eleva el <span class="math inline">\(R^{2}\)</span> del 39% al 71%.</p>
</li>
</ol>
</div>
<div id="solución-al-problema-5.4." class="section level3" number="5.8.4">
<h3>
<span class="header-section-number">5.8.4</span> Solución al Problema 5.4.<a class="anchor" aria-label="anchor" href="#soluci%C3%B3n-al-problema-5.4."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: lower-alpha">
<li><p>Los coeficientes más afectados son la <strong>pendiente</strong> (de 8,0 a 3,5: se reduce a menos de la mitad) y el <strong>coeficiente de determinación</strong> (de 0,83 a 0,26: se hunde). La ordenada también se mueve sensiblemente (de 30 a 45). La explicación es la que el capítulo anticipa: MCO minimiza cuadrados, y un caso muy alejado del patrón general <strong>tira</strong> de la recta hacia sí. El prototipo, con tonelaje muy bajo pese a llevar 15 años en servicio, empuja la recta hacia abajo en su zona central, lo que a la vez achata la pendiente y eleva la ordenada.</p></li>
<li>
<p>Por dos razones que actúan al mismo tiempo:</p>
<ul>
<li>El prototipo dispara la <strong>varianza total</strong> <span class="math inline">\(S_y^{\,2}\)</span> (introduce un valor de <span class="math inline">\(Y\)</span> mucho más alejado de la media).</li>
<li>La nueva recta —forzada a acomodar el prototipo— es peor pronóstico para los 30 casos habituales, lo que dispara la <strong>varianza residual</strong> <span class="math inline">\(S_e^{\,2}\)</span>.</li>
</ul>
<p>Como <span class="math inline">\(R^{2} = 1 - S_e^{\,2}/S_y^{\,2}\)</span>, ambos efectos empujan el cociente al alza y el <span class="math inline">\(R^{2}\)</span> a la baja.</p>
</li>
<li><p><strong>La recta sin prototipo.</strong> El prototipo pertenece de facto a <em>otra población</em> (naves experimentales de un fabricante distinto, con criterios técnicos propios). Como el capítulo 2 recomienda para <em>outliers</em> legítimos que pertenecen a otra población, la decisión razonable es <strong>analizarlo por separado</strong> (o excluirlo del análisis principal). Mezclar la serie regular con un prototipo experimental produce un modelo que no describe bien a ninguno de los dos grupos.</p></li>
<li><p>Antes de dar por bueno el modelo, la primera acción es siempre <strong>mirar la nube de puntos</strong>. Un diagrama de dispersión habría revelado el prototipo como un caso claramente aislado y habría permitido decidir su tratamiento antes de calcular ningún coeficiente. Es la moraleja que atraviesa todo el capítulo, y que Anscombe hará explícita.</p></li>
</ol>
</div>
<div id="solución-al-problema-5.5." class="section level3" number="5.8.5">
<h3>
<span class="header-section-number">5.8.5</span> Solución al Problema 5.5.<a class="anchor" aria-label="anchor" href="#soluci%C3%B3n-al-problema-5.5."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: lower-alpha">
<li><p>Los cinco puntos son <span class="math inline">\((2{,}5;\ 20),\ (7{,}5;\ 22),\ (12{,}5;\ 25),\ (17{,}5;\ 40),\ (25;\ 70)\)</span>. Los <strong>tres primeros</strong> crecen suavemente: apenas 5 mil PAVOs adicionales de coste medio entre los 2,5 y los 12,5 años. A partir de ahí, la curva se <strong>acelera bruscamente</strong>: 15 mil PAVOs más entre los 12,5 y los 17,5 años, y otros 30 mil entre los 17,5 y los 25. <strong>No es un patrón lineal</strong>: hay un umbral perceptible en torno a los 15 años, a partir del cual el coste se dispara.</p></li>
<li><p>Sí es coherente. Un <span class="math inline">\(R^{2}\)</span> del 48% es <strong>modesto</strong> justamente porque la recta única no puede reproducir simultáneamente el tramo plano inicial y la aceleración final. La recta sobreestima el coste en los intervalos jóvenes (predice unos 30 mil PAVOs a los 12,5 años, cuando el dato real es 25) y lo subestima en los intervalos veteranos (predice unos 55 mil a los 25 años, cuando el dato real es 70). Los residuos tendrían un patrón sistemático en forma de <span class="math inline">\(\cup\)</span> invertido, exactamente el que sugiere una relación curva.</p></li>
<li><p>Formas funcionales más adecuadas: una <strong>exponencial</strong> (<span class="math inline">\(\hat{y} = a\cdot b^{x}\)</span>) o una <strong>potencial</strong> (<span class="math inline">\(\hat{y} = a\cdot x^{b}\)</span> con <span class="math inline">\(b &gt; 1\)</span>). Cualquiera de las dos —linealizable con logaritmos, como veremos en la sección de linealización— captaría bien la aceleración final. La regresión de tipo I (los cinco puntos) es la mejor guía para elegir: pide una curva creciente cóncava hacia arriba, no una recta.</p></li>
<li><p>La lectura correcta para el responsable de mantenimiento es la segunda: <strong>“hay un umbral crítico a partir del cual el coste se dispara”</strong>. Es un mensaje <strong>económicamente accionable</strong>: los cargueros que superan los 15 años empiezan a ser desproporcionadamente caros de mantener; conviene contemplar la sustitución o la desinversión en ese umbral, antes de que el coste medio de mantenimiento se acerque al de una nave nueva. La lectura <em>“crece linealmente”</em>, aunque salga de un ajuste MCO honesto, es engañosa y esconde el mensaje operativo importante.</p></li>
</ol>
</div>
<div id="solución-al-problema-5.6." class="section level3" number="5.8.6">
<h3>
<span class="header-section-number">5.8.6</span> Solución al Problema 5.6.<a class="anchor" aria-label="anchor" href="#soluci%C3%B3n-al-problema-5.6."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: lower-alpha">
<li>
<p>De la descomposición de la varianza <span class="math inline">\(S_y^{\,2} = S_{\hat{y}}^{\,2} + S_e^{\,2}\)</span> se despeja:</p>
<p><span class="math display">\[S_{\hat{y}}^{\,2} \;=\; S_y^{\,2} - S_e^{\,2} \;=\; 100 - 25 \;=\; \mathbf{75}.\]</span></p>
</li>
<li>
<p>Aplicando la definición canónica del coeficiente de determinación:</p>
<p><span class="math display">\[R^{2} \;=\; \dfrac{S_{\hat{y}}^{\,2}}{S_y^{\,2}} \;=\; \dfrac{75}{100} \;=\; \mathbf{0{,}75}.\]</span></p>
<p>O equivalentemente, <span class="math inline">\(R^{2} = 1 - S_e^{\,2}/S_y^{\,2} = 1 - 25/100 = 0{,}75\)</span>: las dos expresiones son idénticas.</p>
</li>
<li><p>Un <span class="math inline">\(R^{2}\)</span> del 75% es un <strong>buen ajuste</strong>: la recta reproduce tres cuartas partes de la variabilidad observada en <span class="math inline">\(Y\)</span>. Cabe reportar el modelo con confianza, aunque siempre acompañando el número del examen de residuos.</p></li>
<li><p>Sin explicar: <span class="math inline">\(S_e^{\,2}/S_y^{\,2} = 25/100 = \mathbf{0{,}25}\)</span>, es decir, el <strong>25%</strong> de la variabilidad de <span class="math inline">\(Y\)</span> no queda capturada por la regresión. Se obtiene directamente como cociente entre varianza residual y varianza total, o equivalentemente como <span class="math inline">\(1 - R^{2}\)</span>. En términos prácticos: aunque el modelo es útil, hay una cuarta parte de lo que le pasa a <span class="math inline">\(Y\)</span> que responde a factores que la regresión no observa (otras variables, ruido puro).</p></li>
</ol>
</div>
<div id="solución-al-problema-5.7." class="section level3" number="5.8.7">
<h3>
<span class="header-section-number">5.8.7</span> Solución al Problema 5.7.<a class="anchor" aria-label="anchor" href="#soluci%C3%B3n-al-problema-5.7."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: lower-alpha">
<li>
<p>Según la escala orientativa del capítulo (basada en <span class="math inline">\(|R|\)</span>):</p>
<ul>
<li>Ingresos totales: <span class="math inline">\(|R| = 0{,}28\)</span> → <strong>débil</strong> (0,2-0,5).</li>
<li>Índice de digitalización: <span class="math inline">\(|R| = 0{,}67\)</span> → <strong>moderada</strong>, casi fuerte (0,5-0,7).</li>
<li>Antigüedad media de la flota: <span class="math inline">\(|R| = 0{,}35\)</span> → <strong>débil</strong> (0,2-0,5).</li>
<li>Tamaño de la flota: <span class="math inline">\(|R| = 0{,}17\)</span> → <strong>muy débil o inexistente</strong> (0,0-0,2).</li>
</ul>
<p>En términos de <span class="math inline">\(R^{2}\)</span>: la digitalización captura el 45% de la variabilidad de la rentabilidad, mientras que las otras tres variables recogen entre el 3% y el 12% cada una: mucha menos información.</p>
</li>
<li>
<p><strong>Signos:</strong> positivos para ingresos, digitalización y tamaño; <strong>negativo</strong> para antigüedad de la flota. Lectura sectorial:</p>
<ul>
<li>Digitalización positiva y con la asociación más fuerte: las compañías más digitalizadas tienden a ser más rentables.</li>
<li>Antigüedad negativa: las compañías con flotas más antiguas tienden a ser menos rentables (probablemente por mayores costes de mantenimiento y menor eficiencia operativa).</li>
<li>Ingresos y tamaño con asociaciones débiles: ni facturar mucho ni tener muchas naves basta por sí solo para ser rentable en este sector. La rentabilidad no es cuestión de tamaño.</li>
</ul>
</li>
<li><p><strong>La digitalización</strong>, con diferencia. Es la única que aporta un <span class="math inline">\(R^{2}\)</span> apreciable (0,45); las otras tres, incluidas en solitario, dejan sin explicar más del 85% de la varianza y sirven de bien poco como predictoras.</p></li>
<li>
<p><strong>No.</strong> El <span class="math inline">\(R^{2}\)</span> es una medida <strong>descriptiva</strong> de la calidad del ajuste, no una prueba causal. La asociación observada podría deberse a:</p>
<ul>
<li>Causalidad directa (digitalizar mejora la eficiencia y con ello el margen).</li>
<li>Causalidad inversa (las compañías más rentables tienen recursos para digitalizarse).</li>
<li>Causa común (la calidad de gestión impulsa simultáneamente ambas: rentabilidad <strong>y</strong> digitalización).</li>
</ul>
<p>Sin un modelo causal explícito y sin un diseño de investigación que descarte alternativas, el “digitalizar causa rentabilidad” no está probado por más alto que sea el <span class="math inline">\(R^{2}\)</span>.</p>
</li>
</ol>
</div>
<div id="solución-al-problema-5.8." class="section level3" number="5.8.8">
<h3>
<span class="header-section-number">5.8.8</span> Solución al Problema 5.8.<a class="anchor" aria-label="anchor" href="#soluci%C3%B3n-al-problema-5.8."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: lower-alpha">
<li><p>Solo la <strong>nube (I)</strong> es un ajuste lineal auténtico. La recta captura razonablemente el patrón, y los puntos se dispersan alrededor de ella sin estructura visible. En las tres restantes, la recta y el <span class="math inline">\(R^{2}\)</span> son técnicamente idénticos, pero <strong>no describen</strong> la relación real.</p></li>
<li>
<p>Acciones antes de reportar el modelo:</p>
<ul>
<li>
<strong>Nube (II)</strong> (parabólica): ajustar una <strong>forma funcional cuadrática</strong> (<span class="math inline">\(\hat{y} = a + b\, x + c\, x^{2}\)</span>) o, más en general, cualquier modelo curvo que respete la nube. La recta es una respuesta equivocada a una pregunta correcta.</li>
<li>
<strong>Nube (III)</strong> (<em>outlier</em> vertical): investigar el punto extremo aplicando la lógica del capítulo 2 (error de codificación, caso legítimo excepcional o individuo de otra población), decidir su tratamiento (corregir, excluir, analizar aparte), y <strong>volver a ajustar</strong> la recta sobre los diez restantes, que sí tienen relación lineal casi perfecta.</li>
<li>
<strong>Nube (IV)</strong> (punto de alta palanca): reconocer que los diez casos con <span class="math inline">\(x\)</span> constante <strong>no aportan información sobre la pendiente</strong>; la recta ajustada está literalmente <strong>dictada por un solo punto</strong>. Ninguna conclusión razonable puede basarse en semejante geometría. Convendría explorar por qué hay tan poca variación en <span class="math inline">\(X\)</span>: quizá se está mirando el fenómeno equivocado.</li>
</ul>
</li>
<li><p>La moraleja central es la que Anscombe formuló en 1973: <strong>el <span class="math inline">\(R^{2}\)</span> y los coeficientes de la recta son resúmenes, no diagnósticos</strong>. Cuatro estructuras radicalmente distintas pueden producir los mismos estadísticos. Cualquier análisis serio requiere combinar el resumen numérico con la inspección visual.</p></li>
<li><p>El <strong>diagrama de dispersión</strong> (nube de puntos). Es la herramienta más barata y más potente para detectar problemas de forma, <em>outliers</em> y puntos de alta palanca. <strong>“Mira la nube antes de creerte el número”</strong> es la regla operativa que sintetiza todo el capítulo.</p></li>
</ol>
</div>
<div id="solución-al-problema-5.9." class="section level3" number="5.8.9">
<h3>
<span class="header-section-number">5.8.9</span> Solución al Problema 5.9.<a class="anchor" aria-label="anchor" href="#soluci%C3%B3n-al-problema-5.9."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: lower-alpha">
<li>
<p>Recta de <strong><span class="math inline">\(Y\)</span> sobre <span class="math inline">\(X\)</span></strong>:</p>
<p><span class="math display">\[\hat{b} \;=\; \dfrac{S_{xy}}{S_x^{\,2}} \;=\; \dfrac{3}{4} \;=\; \mathbf{0{,}75}; \qquad \hat{a} \;=\; \overline{y} - \hat{b}\cdot \overline{x} \;=\; 50 - 0{,}75\cdot 20 \;=\; \mathbf{35}.\]</span></p>
<p>Recta: <span class="math inline">\(\hat{y} = 35 + 0{,}75\, x\)</span>.</p>
</li>
<li>
<p>Recta de <strong><span class="math inline">\(X\)</span> sobre <span class="math inline">\(Y\)</span></strong>:</p>
<p><span class="math display">\[\hat{b}' \;=\; \dfrac{S_{xy}}{S_y^{\,2}} \;=\; \dfrac{3}{9} \;\approx\; \mathbf{0{,}333}; \qquad \hat{a}' \;=\; \overline{x} - \hat{b}'\cdot \overline{y} \;=\; 20 - 0{,}333\cdot 50 \;\approx\; \mathbf{3{,}33}.\]</span></p>
<p>Recta: <span class="math inline">\(\hat{x} = 3{,}33 + 0{,}333\, y\)</span>.</p>
</li>
<li>
<p>Coeficiente de determinación por dos vías:</p>
<ul>
<li>Fórmula directa: <span class="math inline">\(R^{2} = S_{xy}^{\,2}/(S_x^{\,2}\cdot S_y^{\,2}) = 3^{2}/(4\cdot 9) = 9/36 = \mathbf{0{,}25}\)</span>.</li>
<li>Producto de pendientes: <span class="math inline">\(\hat{b}\cdot \hat{b}' = 0{,}75 \cdot 0{,}333 = \mathbf{0{,}25}\)</span> ✓.</li>
</ul>
<p>Ambas coinciden: es la identidad canónica <span class="math inline">\(\hat{b}\cdot \hat{b}' = R^{2}\)</span>.</p>
</li>
<li><p><span class="math inline">\(R = +\sqrt{0{,}25} = +\mathbf{0{,}5}\)</span> (con signo positivo porque <span class="math inline">\(S_{xy} &gt; 0\)</span>). Según la escala orientativa del capítulo, es una <strong>relación moderada</strong> (0,5-0,7). Geométricamente, las dos rectas se cruzan en el centro de gravedad <span class="math inline">\((20,\ 50)\)</span> formando una “tijera” <strong>moderadamente abierta</strong>: ni tan estrecha como en el caso <span class="math inline">\(R^{2}\)</span> próximo a 1 (donde casi coincidirían), ni tan abierta como en el caso <span class="math inline">\(R^{2}\)</span> próximo a 0 (donde serían perpendiculares). La apertura del abanico es una lectura visual directa de la intensidad de la relación.</p></li>
</ol>
</div>
<div id="solución-al-problema-5.10." class="section level3" number="5.8.10">
<h3>
<span class="header-section-number">5.8.10</span> Solución al Problema 5.10.<a class="anchor" aria-label="anchor" href="#soluci%C3%B3n-al-problema-5.10."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: lower-alpha">
<li>
<p>Clasificación:</p>
<ul>
<li>Ingresos × Costos operativos: <span class="math inline">\(R = +0{,}96\)</span> → <strong>muy fuerte, positiva</strong>, casi determinista.</li>
<li>Rentabilidad × Digitalización: <span class="math inline">\(R = +0{,}67\)</span> → <strong>moderada</strong>, casi fuerte, positiva.</li>
<li>Antigüedad × Digitalización: <span class="math inline">\(R = -0{,}45\)</span> → <strong>débil</strong>, negativa.</li>
<li>Rutas × Tripulantes: <span class="math inline">\(R = +0{,}88\)</span> → <strong>fuerte</strong>, positiva.</li>
<li>Cantina × Distancia Klendathu: <span class="math inline">\(R = -0{,}03\)</span> → <strong>prácticamente nula</strong>.</li>
</ul>
</li>
<li><p>La relación <strong>casi determinista</strong> es Ingresos × Costos operativos (<span class="math inline">\(R = 0{,}96\)</span>). Explicación económica: ambos indicadores crecen simultáneamente con el <strong>tamaño de la actividad</strong>; una compañía que factura más también incurre en mayores costos operativos, porque opera más rutas, tripula más naves y consume más combustible. Es una relación estructural del funcionamiento del negocio, no una relación causal específica de “los ingresos causan los costes” ni al revés.</p></li>
<li><p><strong>No debería sorprender.</strong> Es coherente con al menos dos mecanismos: (i) las compañías más nuevas se establecen con procesos digitales desde el arranque, mientras que las flotas antiguas suelen operar con sistemas heredados; (ii) los cargueros más veteranos incorporan sensores y arquitecturas de menor generación tecnológica. La antigüedad de la flota tiende a ir con menor digitalización, y <span class="math inline">\(R = -0{,}45\)</span> es la firma cuantitativa de ese vínculo.</p></li>
<li>
<p><strong>Dos errores</strong> en la afirmación del directivo:</p>
<ul>
<li>
<strong>Correlación no es causalidad.</strong> Que rentabilidad y digitalización coincidan en su comportamiento no prueba que la digitalización <em>cause</em> la rentabilidad (puede haber causalidad inversa, o una tercera variable como la calidad de gestión que impulse ambas).</li>
<li>
<strong>Confunde <span class="math inline">\(R\)</span> con <span class="math inline">\(\hat{b}\)</span>.</strong> El 0,67 es un coeficiente de correlación (adimensional, entre <span class="math inline">\(-1\)</span> y <span class="math inline">\(+1\)</span>), <strong>no</strong> una tasa de cambio. La “pendiente” que traduciría un punto adicional de índice de digitalización en puntos porcentuales de rentabilidad es <span class="math inline">\(\hat{b}\)</span>, no <span class="math inline">\(R\)</span>; y ese <span class="math inline">\(\hat{b}\)</span> solo puede leerse de la regresión, no del coeficiente de correlación aislado.</li>
</ul>
</li>
</ol>
</div>
<div id="solución-al-problema-5.11." class="section level3" number="5.8.11">
<h3>
<span class="header-section-number">5.8.11</span> Solución al Problema 5.11.<a class="anchor" aria-label="anchor" href="#soluci%C3%B3n-al-problema-5.11."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: lower-alpha">
<li><p><strong>No.</strong> La primera frase enuncia una <strong>asociación estadística</strong>; la segunda infiere un <strong>efecto causal individual</strong> sobre cualquier compañía que aumente su flota. Es exactamente el salto que el capítulo advierte una y otra vez. Correlación —por alta que sea— no autoriza a hacer prescripciones de gestión.</p></li>
<li>
<p>Hipótesis alternativas:</p>
<ul>
<li>
<strong>Causalidad inversa.</strong> Son las compañías <strong>ya rentables</strong> las que pueden permitirse crecer (comprar más naves), no al revés. El tamaño sería consecuencia de la rentabilidad, no su causa.</li>
<li>
<strong>Causa común.</strong> La <strong>calidad de gestión</strong> (o el conocimiento del mercado, o la posición competitiva heredada) impulsa simultáneamente el crecimiento y la rentabilidad; el crecimiento no genera por sí solo mayor rentabilidad.</li>
<li>
<strong>Efecto escala pero decreciente.</strong> Puede haber un componente causal, pero con rendimientos decrecientes: los primeros cargueros aumentan mucho la rentabilidad; a partir de cierto tamaño, aparecen deseconomías (complejidad organizativa, costes de coordinación). La relación observada podría estar dominada por las compañías pequeñas del sector.</li>
</ul>
</li>
<li><p>Un factor de confusión clásico es la <strong>calidad de gestión / eficiencia operativa / posición competitiva</strong>. Difícil de medir directamente, se traduce simultáneamente en flotas más grandes (la compañía puede comprarlas) y en rentabilidad más alta (la compañía las utiliza bien). Ninguna de las dos causa la otra: ambas son consecuencia del factor oculto. Otros candidatos: <strong>galaxia de operación</strong> (algunas galaxias tienen mercados más lucrativos), <strong>antigüedad de la compañía</strong> (las más veteranas tienen más flota y también más experiencia acumulada), <strong>régimen fiscal</strong>, etc.</p></li>
<li><p>El hallazgo es la firma cuantitativa clásica de que la asociación cruda del “tamaño de flota” contenía en buena parte los efectos de <strong>otras variables</strong>. Al incluir explícitamente galaxia, antigüedad y forma jurídica en el modelo, la variable “tamaño de flota” pierde protagonismo porque su efecto aparente se redistribuye entre las nuevas explicativas. Es el mismo fenómeno de las <strong>variables acechantes</strong> que aparece en la sección de regresión múltiple (y su primo cualitativo, la paradoja de Simpson del capítulo anterior). Refuerza la hipótesis de que la asociación original <strong>no era causal</strong>: el titular necesita reescribirse con humildad.</p></li>
</ol>
</div>
<div id="solución-al-problema-5.12." class="section level3" number="5.8.12">
<h3>
<span class="header-section-number">5.8.12</span> Solución al Problema 5.12.<a class="anchor" aria-label="anchor" href="#soluci%C3%B3n-al-problema-5.12."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: lower-alpha">
<li>
<p>Pendiente del ajuste lineal sobre variables transformadas:</p>
<p><span class="math display">\[b_{\log} \;=\; \dfrac{S_{\log x,\ \log y}}{S^{2}_{\log x}} \;=\; \dfrac{-0{,}476}{0{,}961} \;\approx\; \mathbf{-0{,}495}.\]</span></p>
</li>
<li>
<p>Ordenada del ajuste lineal transformado:</p>
<p><span class="math display">\[\log a \;=\; \overline{\log y} - b_{\log}\cdot \overline{\log x} \;=\; 3{,}396 - (-0{,}495)\cdot 1{,}386 \;=\; 3{,}396 + 0{,}686 \;\approx\; 4{,}082.\]</span></p>
<p>Deshaciendo la transformación: <span class="math inline">\(a = e^{4{,}082} \approx \mathbf{59{,}3}\)</span>.</p>
</li>
<li>
<p>Modelo potencial:</p>
<p><span class="math display">\[\boxed{\;\hat{y} \;=\; 59{,}3\cdot x^{\,-0{,}495}\;}\]</span></p>
<p>Con <span class="math inline">\(R^{2}_{\log} = 0{,}9995\)</span>: la relación en escala log-log es <strong>casi determinista</strong>. Interpretación del exponente:</p>
<ul>
<li>
<strong>Signo negativo</strong>: el tiempo por maniobra <strong>decrece</strong> al aumentar las operaciones acumuladas. Es la firma característica de una curva de aprendizaje.</li>
<li>
<strong>Magnitud próxima a <span class="math inline">\(-0{,}5\)</span></strong>: cada vez que <span class="math inline">\(x\)</span> se multiplica por 10, <span class="math inline">\(y\)</span> se multiplica por <span class="math inline">\(10^{-0{,}495} \approx 0{,}32\)</span>; es decir, el tiempo por maniobra se reduce a un tercio aproximadamente cada vez que las operaciones acumuladas se multiplican por diez. Es una curva de aprendizaje rápida.</li>
</ul>
</li>
<li>
<p>Reducción al <strong>duplicar</strong> las operaciones (<span class="math inline">\(x \to 2x\)</span>):</p>
<p><span class="math display">\[1 - 2^{b_{\log}} \;=\; 1 - 2^{-0{,}495} \;\approx\; 1 - 0{,}710 \;\approx\; 0{,}290 \;=\; \mathbf{29\%}.\]</span></p>
<p>El jefe de estudios está <strong>aproximadamente</strong> en lo cierto: el tiempo se reduce alrededor del 29% cada vez que las operaciones acumuladas se duplican, cifra cercana al “tercio” (33%) que menciona. Sería más preciso decir <em>“casi un 30%”</em>, pero el orden de magnitud es correcto y su afirmación es defendible en un informe divulgativo.</p>
</li>
</ol>
</div>
<div id="solución-al-problema-5.13." class="section level3" number="5.8.13">
<h3>
<span class="header-section-number">5.8.13</span> Solución al Problema 5.13.<a class="anchor" aria-label="anchor" href="#soluci%C3%B3n-al-problema-5.13."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: lower-alpha">
<li>
<p>El <span class="math inline">\(R^{2}\)</span> pasa de 0,39 a 0,71. La proporción <strong>adicional</strong> de variabilidad del tonelaje capturada por el Modelo B respecto del Modelo A es:</p>
<p><span class="math display">\[R^{2}_B - R^{2}_A \;=\; 0{,}71 - 0{,}39 \;=\; \mathbf{0{,}32} \;=\; 32\%.\]</span></p>
<p>Incluir el astillero como segunda variable explicativa <strong>añade</strong> un 32% de la variabilidad total del tonelaje al modelo. Es una mejora sustancial: casi se duplica el <span class="math inline">\(R^{2}\)</span> del modelo simple.</p>
</li>
<li>
<p>La pendiente de antigüedad se derrumba: pasa de 12,6 a apenas 1,44 (menos de una octava parte). La explicación es clave:</p>
<ul>
<li>En el <strong>Modelo A</strong>, la pendiente 12,6 no era el “efecto puro” de la antigüedad; era el <strong>efecto de la antigüedad + el efecto disfrazado del astillero</strong>. Como los astilleros más productivos y con carteras más pesadas suelen tener flotas más veteranas, la antigüedad estaba <strong>capturando</strong> también la parte del tonelaje que se debía al astillero.</li>
<li>En el <strong>Modelo B</strong>, al <strong>controlar</strong> por el astillero (variable ahora incluida en el modelo), la pendiente de antigüedad recupera su interpretación limpia: cada año adicional se asocia a solo 1,44 mil toneladas más, manteniendo constante la identidad del astillero. Casi todo el “efecto antigüedad” del modelo simple era en realidad <strong>efecto astillero mal atribuido</strong>.</li>
</ul>
<p>La lección es económica y estadística a la vez: la antigüedad, por sí sola, dice muy poco sobre el tonelaje una vez que sabemos qué astillero ha construido el carguero.</p>
</li>
<li>
<p>Interpretación de las <em>dummies</em> (con ARCTURUS como categoría de referencia):</p>
<ul>
<li>Coeficiente de <span class="math inline">\(D_K = +107\)</span>: un carguero de <strong>KORRIGAN</strong> pesa, en promedio, unos <strong>107 mil toneladas más</strong> que uno equivalente de ARCTURUS de la misma antigüedad.</li>
<li>Coeficiente de <span class="math inline">\(D_S = -111\)</span>: un carguero de <strong>SELENE</strong> pesa, en promedio, unos <strong>111 mil toneladas menos</strong> que uno equivalente de ARCTURUS de la misma antigüedad.</li>
</ul>
<p>Es decir, hay una jerarquía clara por astillero: <strong>KORRIGAN &gt; ARCTURUS &gt; SELENE</strong> en términos de tonelaje típico. La antigüedad, dentro de cada astillero, matiza esa jerarquía pero apenas la mueve.</p>
</li>
<li>
<p>Porque cuando se comparan modelos con <strong>distinto número de parámetros</strong>, el <span class="math inline">\(R^{2}\)</span> ordinario <strong>siempre crece</strong> —o al menos no baja— al añadir variables, aunque estas sean ruido puro. Comparar el Modelo B con el A por <span class="math inline">\(R^{2}\)</span> ordinario es informativo, pero técnicamente sesgado a favor del modelo con más variables. El <span class="math inline">\(R^{2}\)</span> <strong>ajustado</strong> penaliza la introducción de parámetros y solo crece cuando la nueva variable <strong>aporta más de lo que cuesta</strong>. En este caso, <span class="math inline">\(R^{2}_{\text{aj}} = 0{,}69\)</span> apenas se aparta del <span class="math inline">\(R^{2} = 0{,}71\)</span>, señal de que la mejora es <strong>real</strong> y no un artefacto de haber añadido parámetros. Si al añadir el astillero el <span class="math inline">\(R^{2}\)</span> hubiera crecido de 0,39 a 0,42 pero el <span class="math inline">\(R^{2}_{\text{aj}}\)</span> se hubiera quedado en 0,38, la conclusión sería la opuesta: ganancia marginal insuficiente.</p>
<p>En el Modelo A no reportamos <span class="math inline">\(R^{2}\)</span> ajustado porque, con una sola variable, el ajuste importa poco y <span class="math inline">\(R^{2}\)</span> y <span class="math inline">\(R^{2}_{\text{aj}}\)</span> son casi iguales.</p>
</li>
<li>
<p>Se llama fenómeno de <strong>variable acechante</strong> (<em>lurking variable</em>): una variable no incluida en el modelo que, sin embargo, está correlacionada tanto con la explicativa como con la explicada, y arrastra parte del efecto aparente de la primera sobre la segunda. Es el equivalente <strong>cuantitativo</strong> de la <strong>paradoja de Simpson</strong> que vimos en el capítulo anterior sobre tablas de contingencia: allí, la relación entre dos atributos se invertía al desagregar por un tercero; aquí, la pendiente de una regresión simple se altera radicalmente al añadir la variable correcta. En ambos casos el remedio es el mismo: <strong>incluir la variable acechante en el análisis</strong> —aquí, como variable explicativa adicional; allí, como criterio de estratificación— para que los coeficientes recuperen su lectura limpia.</p>
<p>Es, quizá, el mensaje más valioso que el estudiante de ADE debe llevarse de este bloque: casi ninguna relación empresarial es entre dos variables aisladas; casi siempre hay una tercera —a menudo la calidad de gestión, el tamaño, el sector— acechando detrás de los coeficientes.</p>
</li>
</ol>
</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="variable-estadistica-bidimensional.html"><span class="header-section-number">4</span> Variable estadística bidimensional y n-dimensional.</a></div>
<div class="next"><a href="numeros-indice.html"><span class="header-section-number">6</span> Números índice.</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#regresion-correlacion"><span class="header-section-number">5</span> Regresión y correlación.</a></li>
<li>
<a class="nav-link" href="#regresion-idea"><span class="header-section-number">5.1</span> Regresión: idea general.</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#regresion-simple-multiple"><span class="header-section-number">5.1.1</span> Regresión simple, regresión múltiple.</a></li>
<li><a class="nav-link" href="#regresion-tipos"><span class="header-section-number">5.1.2</span> Dos caminos hacia la regresión: tipo I y tipo II.</a></li>
<li><a class="nav-link" href="#forma-funcional"><span class="header-section-number">5.1.3</span> Forma funcional y parámetros.</a></li>
<li><a class="nav-link" href="#minimos-cuadrados"><span class="header-section-number">5.1.4</span> El criterio de estimación: mínimos cuadrados.</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#regresion-lineal-simple"><span class="header-section-number">5.2</span> Regresión lineal simple.</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#interpretacion-coeficientes"><span class="header-section-number">5.2.1</span> Interpretación de los coeficientes.</a></li>
<li><a class="nav-link" href="#ejemplo-astilleros-reg"><span class="header-section-number">5.2.2</span> Un ejemplo completo: antigüedad y tonelaje en la flota de astilleros.</a></li>
<li><a class="nav-link" href="#tipo1-astilleros"><span class="header-section-number">5.2.3</span> Regresión de tipo I sobre la flota.</a></li>
<li><a class="nav-link" href="#prediccion-extrapolacion"><span class="header-section-number">5.2.4</span> Predicción y una advertencia importante.</a></li>
<li><a class="nav-link" href="#outliers"><span class="header-section-number">5.2.5</span> La sensibilidad a valores atípicos.</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#bondad-ajuste"><span class="header-section-number">5.3</span> Bondad del ajuste: el coeficiente de determinación.</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#R2-astilleros"><span class="header-section-number">5.3.1</span> Vuelta a la flota.</a></li>
<li><a class="nav-link" href="#residuos-diagnostico"><span class="header-section-number">5.3.2</span> Los residuos como diagnóstico.</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#correlacion"><span class="header-section-number">5.4</span> Correlación.</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#R-astilleros"><span class="header-section-number">5.4.1</span> El coeficiente de correlación en la flota.</a></li>
<li><a class="nav-link" href="#dos-rectas"><span class="header-section-number">5.4.2</span> Las dos rectas de regresión.</a></li>
<li><a class="nav-link" href="#R-rstars-ing-costop"><span class="header-section-number">5.4.3</span> Un ejemplo con ajuste excelente: ingresos y costos operativos en R-Stars.</a></li>
<li><a class="nav-link" href="#anscombe"><span class="header-section-number">5.4.4</span> Un aviso importante: el cuarteto de Anscombe.</a></li>
<li><a class="nav-link" href="#correlacion-no-causal"><span class="header-section-number">5.4.5</span> Correlación no implica causalidad (bis).</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#generalizacion"><span class="header-section-number">5.5</span> Generalización de la regresión.</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#no-lineales"><span class="header-section-number">5.5.1</span> Casos no lineales: linealización.</a></li>
<li><a class="nav-link" href="#curva-aprendizaje"><span class="header-section-number">5.5.2</span> Un caso ilustrativo: la curva de aprendizaje en Hyperdrive Express.</a></li>
<li><a class="nav-link" href="#regresion-multiple"><span class="header-section-number">5.5.3</span> Regresión múltiple.</a></li>
<li><a class="nav-link" href="#r2-ajustado"><span class="header-section-number">5.5.4</span> Un aviso conceptual sobre el R² ajustado.</a></li>
</ul>
</li>
<li><a class="nav-link" href="#recapitulacion-cap05"><span class="header-section-number">5.6</span> Recapitulación.</a></li>
<li>
<a class="nav-link" href="#problemas-cap05"><span class="header-section-number">5.7</span> Problemas propuestos.</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#problema-5.1.-leer-una-recta-ya-ajustada."><span class="header-section-number">5.7.1</span> Problema 5.1. Leer una recta ya ajustada.</a></li>
<li><a class="nav-link" href="#problema-5.2.-calcular-la-recta-desde-cero."><span class="header-section-number">5.7.2</span> Problema 5.2. Calcular la recta desde cero.</a></li>
<li><a class="nav-link" href="#problema-5.3.-predicci%C3%B3n-y-extrapolaci%C3%B3n-en-la-flota."><span class="header-section-number">5.7.3</span> Problema 5.3. Predicción y extrapolación en la flota.</a></li>
<li><a class="nav-link" href="#problema-5.4.-el-efecto-de-un-outlier-sobre-la-recta."><span class="header-section-number">5.7.4</span> Problema 5.4. El efecto de un outlier sobre la recta.</a></li>
<li><a class="nav-link" href="#problema-5.5.-regresi%C3%B3n-de-tipo-i-y-tipo-ii-sobre-la-misma-tabla."><span class="header-section-number">5.7.5</span> Problema 5.5. Regresión de tipo I y tipo II sobre la misma tabla.</a></li>
<li><a class="nav-link" href="#problema-5.6.-descomposici%C3%B3n-de-la-varianza."><span class="header-section-number">5.7.6</span> Problema 5.6. Descomposición de la varianza.</a></li>
<li><a class="nav-link" href="#problema-5.7.-comparar-cuatro-regresiones-por-su-r2."><span class="header-section-number">5.7.7</span> Problema 5.7. Comparar cuatro regresiones por su \(R^{2}\).</a></li>
<li><a class="nav-link" href="#problema-5.8.-cuarteto-de-anscombe-en-clave-r-stars."><span class="header-section-number">5.7.8</span> Problema 5.8. Cuarteto de Anscombe en clave R-Stars.</a></li>
<li><a class="nav-link" href="#problema-5.9.-las-dos-rectas-y-r2."><span class="header-section-number">5.7.9</span> Problema 5.9. Las dos rectas y \(R^{2}\).</a></li>
<li><a class="nav-link" href="#problema-5.10.-interpretar-coeficientes-de-correlaci%C3%B3n."><span class="header-section-number">5.7.10</span> Problema 5.10. Interpretar coeficientes de correlación.</a></li>
<li><a class="nav-link" href="#problema-5.11.-correlaci%C3%B3n-y-causalidad-segunda-vuelta."><span class="header-section-number">5.7.11</span> Problema 5.11. Correlación y causalidad (segunda vuelta).</a></li>
<li><a class="nav-link" href="#problema-5.12.-linealizaci%C3%B3n-curva-de-aprendizaje-en-enterprise-logistics."><span class="header-section-number">5.7.12</span> Problema 5.12. Linealización: curva de aprendizaje en Enterprise Logistics.</a></li>
<li><a class="nav-link" href="#problema-5.13.-ejercicio-integrador-la-variable-acechante-en-la-flota."><span class="header-section-number">5.7.13</span> Problema 5.13. Ejercicio integrador: la variable acechante en la flota.</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#soluciones-cap05"><span class="header-section-number">5.8</span> Soluciones a los problemas propuestos.</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#soluci%C3%B3n-al-problema-5.1."><span class="header-section-number">5.8.1</span> Solución al Problema 5.1.</a></li>
<li><a class="nav-link" href="#soluci%C3%B3n-al-problema-5.2."><span class="header-section-number">5.8.2</span> Solución al Problema 5.2.</a></li>
<li><a class="nav-link" href="#soluci%C3%B3n-al-problema-5.3."><span class="header-section-number">5.8.3</span> Solución al Problema 5.3.</a></li>
<li><a class="nav-link" href="#soluci%C3%B3n-al-problema-5.4."><span class="header-section-number">5.8.4</span> Solución al Problema 5.4.</a></li>
<li><a class="nav-link" href="#soluci%C3%B3n-al-problema-5.5."><span class="header-section-number">5.8.5</span> Solución al Problema 5.5.</a></li>
<li><a class="nav-link" href="#soluci%C3%B3n-al-problema-5.6."><span class="header-section-number">5.8.6</span> Solución al Problema 5.6.</a></li>
<li><a class="nav-link" href="#soluci%C3%B3n-al-problema-5.7."><span class="header-section-number">5.8.7</span> Solución al Problema 5.7.</a></li>
<li><a class="nav-link" href="#soluci%C3%B3n-al-problema-5.8."><span class="header-section-number">5.8.8</span> Solución al Problema 5.8.</a></li>
<li><a class="nav-link" href="#soluci%C3%B3n-al-problema-5.9."><span class="header-section-number">5.8.9</span> Solución al Problema 5.9.</a></li>
<li><a class="nav-link" href="#soluci%C3%B3n-al-problema-5.10."><span class="header-section-number">5.8.10</span> Solución al Problema 5.10.</a></li>
<li><a class="nav-link" href="#soluci%C3%B3n-al-problema-5.11."><span class="header-section-number">5.8.11</span> Solución al Problema 5.11.</a></li>
<li><a class="nav-link" href="#soluci%C3%B3n-al-problema-5.12."><span class="header-section-number">5.8.12</span> Solución al Problema 5.12.</a></li>
<li><a class="nav-link" href="#soluci%C3%B3n-al-problema-5.13."><span class="header-section-number">5.8.13</span> Solución al Problema 5.13.</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Estadística Empresarial</strong>" was written by Miguel Ángel Tarancón Morán. It was last built on 2026-08-25.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
